apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: default
stringData:
    #ENC[AES256_GCM,data:7v/JqwfYsp6wAbay9coIMoISZCYeJPr8FnPMk6iud4ziY8euc/DaaVPrx1Gs5r9Iv2nu6tVG2TwIIGrrYQ==,iv:yWt/t/G6FycQ3co+fBMd1GuPUbwG+7KZuXAwZIbBUeQ=,tag:5q0CIr2o/q08/xLtUUfEww==,type:comment]
    #ENC[AES256_GCM,data:4MG7Z2aCRYrgPS8o0pNVUBajuyY3Wo6aYMbELoP5vqLHhlSPumPUsk6QjZGpALTrRlFzYdR82/E4c54vXRx4ZsXVYHSgKeQ=,iv:yITlTWHvYN9zJo2q7axPGaDXYb5llgvuOV4W6mg7w3Q=,tag:yKLyB3Qt6/6aG/1wmXd+Zg==,type:comment]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:pAMaNVpsP0YMLul8a3vbpoEAbxiUCoOlYlKiP9AqQ9BO9o4eu3Lakco0sWQ=,iv:6hpAqH7tOrgn+0wB3CVZzJ8Y7AUl5X77YXSTk3GVaBI=,tag:1zABIC6UD5l+NWpuBvs3Bg==,type:str]
    #ENC[AES256_GCM,data:fBmoIhFhjonYpVrxOd2I7ChwkCH5IIYHfH2q1GH9LOrjdlGm26TVARuC2IrP273nWU594lUm6zn/yYj7Fqh25Dno6iWcRjJ+UyxdOjQhb6XdVy1Gn102,iv:RM2Hy+cKUA6WID2a2S+22uT4piyf0+WadO7NgE8ZSRU=,tag:OjROJzGa6PvFvLnZNdGb7g==,type:comment]
    SMTP_USER: ENC[AES256_GCM,data:VJO/Qo0O,iv:cp3FqhtEN/2iXj7WRoQhwkew3AdB6egE9v+O6+uQlzM=,tag:ZE/twyJdRy+WiLzzFMoCRA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:kZwhtXMTBI9RU/gHNF/sNLnQImxyryadlK7e626dw7cpPV4/,iv:cpel5MgJ4xWf7md2/ceHuDoBanUEkUiovl/87Okp3h8=,tag:3DKQS5qDIOHsV2lU4pobDw==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cnMyMExVQm5mMG8xS1lu
            WGdzTUVMSEhCUHFxMjE1Zi9mdDlmZnVaZzJVCi83RGxDakRpd0cvVkZTWjRkMVZ6
            NHdQQlgzRDJXWC9kVzhMZ0JYQ0xsQlkKLS0tIFYvZXVZTlhhdjFtTDBZbEVHc0Ew
            MHpHSG1rL2tiVTlBQUNCVkQxeFhiYTgK0WqCs6ktAsbSmDHxFqhupoMhNLdWXCtj
            1v62dzXpvGYCB6Br8Lyy7HexjeGOe1JhTU8/6e6K7qGhKVrPBR89Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T01:23:29Z"
    mac: ENC[AES256_GCM,data:aQ+StOJ8f25ejvt6Gn9wPDZ4LiC7gKyUZ4G0I7POBPWME9Jh9Tgn7mhyCZeRXnNTsuQ2HVeDO7TdoZ/MJ6C7G4PzXVR0fUNPbFihxx6DyiUwRpim4atSjEgktKzY1kTX5/3oqXhhJwVkOPm5UfsA0LRNTiqW49tfFQdAqEGbu84=,iv:cxznemTV8gmPsN4GoToZthT911lCzfDZo4XLV9KA/Y0=,tag:5eGrgQ2pYHJQ/63NcUEjJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
