apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: backup-scheduled
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 */6 * * *"
    suspend: false
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 3Gi
      accessModes:
        - ReadWriteMany
      storageClassName: longhorn
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi