apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-operator
resources:
  - backup.yaml
  - restore.yaml # To restore, ensure that backup pvc has the data
  - database.yaml
  - mariadb.yaml

  
