apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  image:  mariadb:lts
  replicas: 3
  replication:
    enabled: true
    primary:
      automaticFailover: true
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password
  service:
    type: LoadBalancer
  primaryService:
    type: LoadBalancer
  secondaryService:
    type: LoadBalancer
  volumeClaimTemplate:
    resources:
      requests:
        storage: 3Gi
    accessModes:
      - ReadWriteMany