apiVersion: v1
kind: Secret
metadata:
    name: netdata-claiming
    namespace: netdata
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:WqR3WsJwcSyoGjR0S7K8tGMi9u2dZiIVQ2pyju5y+Ssi1bH47IXEgqMCXnZY+eYrZkBnWP6Tu5VOKaCfF1qfdBQ3MvN+m8hMVueFmnJgux2IyLK+XISsCf8qVhFsXeNy1jAW6E9iHNWxsNEIXx02YhXBL1LSuvBd/bPt7OpVZkzukyf1Yzi/RP74wI6nF4RpGvcGDmosnvnCqvA0jS+1K1tvgqXlGsyUQavW+JlQSIFAITU913ci5PDojnVf4hbFxfBRmJSmcrWhHxvvAvvEB2c3Nt7LQl03b4OEQFrPNSf+Fs0Vu7b3NVek14MDwxgI2urOPqbOGtJ9OMQVIiyjL7FvfKtG+rSEgSEcdk6mUDBDMxqREX83yBdD37KLTp7L++rBlMJSSe6k/yPz8YS52b5S3EmLFtiwzOwCxp2Z3erxMGtslub/GKYCZvhVcdqrj4gzCEg+A6d55uvwSyQ2Sx9dl3I2y2YW7YTc1Z8IqMMdgZDBN2JjxChr4bvF1cXipBhf+tNkVfirvjfbStFenTrkyO54e1l+YF7WTJ5Ko4/85foNf1wizJ8UARqw,iv:6N6w+bJwxqu+X4oqnfKIGsR3F8chFWzJSRS9OmnYOIg=,tag:68RwV2c+XDeMf6BdXroVJA==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVGFpM3MrZ28zVWRmOGpJ
            bnhDOFprVUVWN3Q0clNqd1AzQW9sVzk5RGhrCmNpSUNpeHpmYlloNmgxZnhlY1hY
            a2JaR0syWGx6VEZ1TXdBVG00ekRpcFUKLS0tIEtQM2FXdlZlNGZpYk9rWXdRVFdT
            aFFQK2RDL2xWdVN6RWRoZ24zUTRkNXcK0adbYh5MS2/Fq8N/+a7MQu4g5IPbRI9d
            QQUBrTif56vawfC7lBrT2I+EMlX1oQP2aZXORUN0g5glMZjKTZQ7Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T13:42:02Z"
    mac: ENC[AES256_GCM,data:mTh2rILqGCCBz7kciYSvjzWp6aAdAgstav871VDN6orUPoUEuVAfD+rgbrTR+c6qjqdvZ5eSfQLSDmdxHi2BXqhpIHjL7cFmrymuEDgTuuqBcShFEEIq9viiy6Vaa+ipFX8/JHvnrY1ixJoChYvdiSSzNwZacxi3cCygI7isXMU=,iv:Dm82EqPhmjc2Xi/WQafU4ijb3OJTW2N9iuSG0Y3w9IQ=,tag:9ZvS6J5Njc5rkBaD2mNueg==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
