apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secret.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  dependsOn:
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: cloudflare
  path: ./clusters/home/cloudflare
  prune: true
  wait: true
  interval: 1m
