apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - secret.yaml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-provisioner
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  path: ./clusters/home/cloudflare
  wait: true
  dependsOn:
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: sealed-secrets
    namespace: flux-system
