apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/cloudflare-tunnel
      version: "0.2.x"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare
      interval: 1m
  values:
    cloudflare:
      ingress:
        # We point cloudflare to our nginx ingress to receive all requests
        - service: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
