apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sops
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: "0.x.x"
  interval: 1h0m0s
  releaseName: sops-controller
  targetNamespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # add secret here
