apiVersion: v1
data:
  age-key.txt: IyBjcmVhdGVkOiAyMDIzLTExLTIxVDE4OjA2OjI1KzA4OjAwCiMgcHVibGljIGtleTogYWdlMXY1eWg1Znl4Nms4cDByMmpqbGpudHNwcHhrdXVkem4zZGx4dDYyNHl3MnJwYTZmanl1anNscG5lNHAKQUdFLVNFQ1JFVC1LRVktMVkzSk5GWDVMN05FOVpHU1hNOEFMRjJITDhEWTM5WVM5WVZBOFdXU0dBS1VUNVRSSEhHR1NNTVM5NU4K
kind: Secret
metadata:
  creationTimestamp: null
  name: age
