apiVersion: v1
kind: Secret
metadata:
    name: zenos-runner-registration
    namespace: github-runners
type: Opaque
stringData:
    RUNNER_TOKEN: ""
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSmc1WEhMMDlVbG80L3dt
            VU9HSGV4Zkd4ZGpLdFJRRXhnODZSNlZOZ0NnCjBlRVgvZElTNkthNGpSTklXS1Vr
            andKSkFGUXVZOFNPTElKWDhyRWFHYWcKLS0tIEFJbHVmMkx3N0wvSUV3MGc3a1dE
            TUNyb3BBQ3Z1M2NHS1VpaUJaWm5rUHcKdGHovapuucPtpVJ77VKqLSZ+00dD4jxX
            W5INlvttQxJ/a6vHKMM+zLVc0xoS/4H1oKDsAaX9ueNyLdCoHhN56w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T21:58:49Z"
    mac: ENC[AES256_GCM,data:F9hLpaCFKy98DLk3ouxrWJ3JyO7XyqManU5kp/8I/iR3nHRW4ht1JY5WJ1SYrvMeeYJyFQAjG9zhCTx9ljFCN806pFFPNtorRFFuf/I/BtgfuwFfbqXnHbOoNJljx7o2HJ0GxAjMjokk04yIiezqXe3rSy0S5H/TsqJOwyiD5I0=,iv:IZkIKhR5ijyLOySs93lBxCHe1jb3mbi4g1OX+EgHCsk=,tag:re3S1Cg+GFYb0kukMZdTIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
