apiVersion: v1
kind: Secret
metadata:
    name: zenos-runner-registration
    namespace: github-runners
type: Opaque
stringData:
    RUNNER_TOKEN: ""
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSmc1WEhMMDlVbG80L3dt
            VU9HSGV4Zkd4ZGpLdFJRRXhnODZSNlZOZ0NnCjBlRVgvZElTNkthNGpSTklXS1Vr
            andKSkFGUXVZOFNPTElKWDhyRWFHYWcKLS0tIEFJbHVmMkx3N0wvSUV3MGc3a1dE
            TUNyb3BBQ3Z1M2NHS1VpaUJaWm5rUHcKdGHovapuucPtpVJ77VKqLSZ+00dD4jxX
            W5INlvttQxJ/a6vHKMM+zLVc0xoS/4H1oKDsAaX9ueNyLdCoHhN56w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T09:12:05Z"
    mac: ENC[AES256_GCM,data:cuCzg/+QU1k1pve3KJFBWLGANeJddGBHuQytqmodC75P9/AiW6fusmagIW/KhyM5KmeWlNZ5C0o05DSii+jcIKXbyUddIYo73mLsdK5EDtOiEUD/HTPnptlkfvIuMX3Sr+JtePvVqtBF1iPKdFW9Sof6iNli32+6SveKRfSmqJI=,iv:HN94BEUghEMJHvgXxt3awky3cmWmcgDH7bD99MjzH3k=,tag:+nlIPMBaiRI9cYFr9f7NHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
