apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |
    - Bookmarks:
      - Github Code Search:
          - icon: github-light
            href: https://cs.github.com/
