apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      version: "1.x.x"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: default
      interval: 1m
  values:
    config:
      bookmarks:
        - Bookmarks:
          - Github Code Search:
              - icon: github-light
                href: https://cs.github.com/
          - Dev Resources:
              - abbr: DR
                href: https://resource.fyi
          - Dev Shirts:
              - abbr: DS
                href: https://www.devshirt.club/
          - Javascript Patterns:
              - icon: javascript
                href: https://javascriptpatterns.vercel.app/patterns
          - Uiverse:
              - abbr: UI
                href: https://uiverse.io/all
          - Advanced JS Functions:
              - abbr: AF
                href: https://www.paulsblog.dev/advanced-javascript-functions-to-improve-code-quality/
        - Software News:
          - Dev (Top of the week):
              - icon: https://d2fltix0v2e0sb.cloudfront.net/dev-black.png
                href: https://dev.to/top/week
          - Daily Dev:
              - abbr: DD
                href: https://app.daily.dev/
          - Github Trending:
              - icon: github-light
                href: https://github.com/trending?since=weekly
        - Reddit Threads:
          - r/ProgrammerHumour:
              - icon: reddit
                href: https://www.reddit.com/r/ProgrammerHumor/top/?t=week
          - r/unixporn:
              - icon: https://styles.redditmedia.com/t5_2sx2i/styles/communityIcon_7fixeonxbxd41.png?width=256&v=enabled&s=09e1c0d643c91e5dada2c7f73adb4effdb0bdf7d
                href: https://www.reddit.com/r/unixporn/top/?t=week
          - r/selfhosted:
              - icon: https://styles.redditmedia.com/t5_32hch/styles/communityIcon_b2t5inv46z331.png?width=256&v=enabled&s=5049c971d4eaf5f8c05ee019586381828d5ef56e
                href: https://www.reddit.com/r/selfhosted/top/?t=week
        - Programming & trends:
            - NodeJS Weekly:
                - icon: node.js
                  href: https://nodeweekly.com
            - Javascript Weekly:
                - icon: javascript
                  href: https://javascriptweekly.com
            - Golang Weekly:
                - icon: golang
                  href: https://golangweekly.com
            - Rust Weekly:
                - icon: rust
                  href: https://this-week-in-rust.org/
            - Unzip:
                - abbr: UZ
                  href: https://unzip.dev/archive/
      services:
        - Infrastructure:
            - Proxmox:
                href: https://pve.pacholoamit.com/
                description: Server management
                icon: proxmox.png
                ping: https://pve.pacholoamit.com/
                widget:
                  type: proxmox
                  url: https://pve.pacholoamit.com
                  username: api@pam!api
                  password: ***REMOVED***
            - Longhorn:
                href: https://longhorn.pacholoamit.com/
                description: Cloud native distributed block storage
                icon: longhorn.png
                ping: https://longhorn.pacholoamit.com/
            - Weaveworks Dashboard:
                href: https://weave.pacholoamit.com/
                description: Weave K8s Flux Dashboard
                icon: https://avatars.githubusercontent.com/u/9976052?s=200&v=4
                ping: https://weave.pacholoamit.com/

        - Apps/Services:
            - My Second Service:
                href: http://localhost/
                description: Homepage is the best

      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - longhorn:
            # Show the expanded view
            expanded: true
            # Shows a node representing the aggregate values
            total: true
            # Shows the node names as labels
            labels: true
            # Show the nodes
            nodes: true        
        - search:
            provider: google
            target: _blank
      kubernetes:
        mode: cluster
      settings:

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true

    ingress:
      main:
        enabled: true
        annotations:
          # Example annotations to add Homepage to your Homepage!
          gethomepage.dev/enabled: "false"
          gethomepage.dev/name: "Pach's Homepage"
          gethomepage.dev/description: "Dynamically Detected Homepage"
          gethomepage.dev/group: "Dynamic"
          gethomepage.dev/icon: "homepage.png"
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: homelab.pacholoamit.com
            paths:
              - path: /
                pathType: Prefix

    
