# LINK TO INSPIRATION
# https://github.dev/Michaelpalacce/HomeLab
# Search for SOPS implementation
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: homepage
      version: "1.x.x"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: default
      interval: 1m
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.8.0
    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage
      service:
        main:
          ports:
            http:
              port: 3000

    # This enables the service account to access the necessary resources
    enableRbac: true
    config:
      useExistingConfigMap: homepage-config

    ingress:
      main:
        enabled: false
        annotations:
        hosts:
          - host: homelab.pacholoamit.com
            paths:
              - path: /
                pathType: Prefix

    
