# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vaultwarden
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: vaultwarden
#   template:
#     metadata:
#       labels:
#         app: vaultwarden
#     spec:
#       containers:
#         - name: vaultwarden
#           image: vaultwarden/server:1.30.1
#           volumeMounts:
#             - name: vaultwarden-volume
#               mountPath: /data
#           env:
#             - name: LOG_FILE
#               value: /data/vaultwarden.log
#             - name: LOG_LEVEL
#               value: warn
#             - name: SIGNUPS_ALLOWED
#               value: "true"
#             - name: SHOW_PASSWORD_HINT
#               value: "true"
#       volumes:
#         - name: vaultwarden-volume
#           persistentVolumeClaim:
#             claimName: vaultwarden-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: default
spec:
  serviceName: "vaultwarden"
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.30.1
          volumeMounts:
            - name: vaultwarden-volume
              mountPath: /data
          env:
            - name: LOG_FILE
              value: /data/vaultwarden.log
            - name: LOG_LEVEL
              value: warn
            - name: SIGNUPS_ALLOWED
              value: "true"
            - name: SHOW_PASSWORD_HINT
              value: "true"
  volumeClaimTemplates:
    - metadata:
        name: vaultwarden-volume
      spec:
        storageClassName: longhorn
        # dataSource From previous migration of data from deployment
        dataSource:
          kind: PersistentVolumeClaim
          name: vaultwarden-pvc
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 5Gi
