apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws
  namespace: velero
spec:
  encryptedData:
    cloud: AgAbxqdP+Hl7YfDawNh+9G86Vn1MN57CF+i6GM66rncRlpNBTKudet6EvCA92cOFRdrdp9LDstHlD94g0F5f9mdbau6AiorUpscwci7CBB9o4PAZHHzlwir+NdmJL3lCgDdfE7BU1Yg9V3AeiPbTPSfcHef3Mpxq9Zr2gvLc2F9cA2rxZCKLk0ZzhfYBqsWQ6TG+rLkRSqKSR6mFQxuZSSX0Q4y+c9W1Sopq56hKb0yXn6qtlh1t+XI6vjKrtSQ9b1gBLvUB+1q3rEN6A+cgWmxpVJskgsY/6FZgdsDwoYzOKtxjedFulmWXZbbSE+v9GHNhrcI7NoBGV5J/3447vQUFjFGnbl/89uIanOnWrY5KKVCg6Ll2bBS2gkMdW+A9EVch/TGwCtQBIU3MOpNESLkVTy7XYTUkKcn+Xyb0xk6RBp2/7pOLKSAwAJ1oEVvQy0W/7ucVk7hDZJzyZh2mMpPIbsYaMtDA/EUqNCQVbCBv49lfSikTw8UaL1IYk+QUtYFU1orGFmyEy1X1nzoENYt5seW/kE+ynLEd4kcGdwBEDVQcJjOp95hw+q6gfuDGnqnvNuEH050Gt7vDz94i/gEhVLXr1CZnBfvTqz36xjslUWa4mSzRzhC5Ux1Yj0BLqazfi67jYQpxs9iDvbD5utaw3E4a4ipkS7H1pC9fpJh+RaovG79h2ZsZ/Hbsry+/FQb4GqXW/qs/d2oLaiSG614v4D1Rgc9ww6wsllqnMQ46ufoZBvbZndnD3xhWfXpYbD9c8s6x/tIrJVXgw/AtFc6fnXBa5o/e1N3IAE6kIcjzWZp8K4EV3HJZ8Ospci45cIOFIfzEHf8vERTyZQswuJ25OHG9
  template:
    metadata:
      creationTimestamp: null
      name: aws
      namespace: velero

