apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws
  namespace: velero
spec:
  encryptedData:
    aws-credentials: AgB3wRYxqJiEXgCm/BxwrYiimLnIDTbSGcnB0alNArvuKEK/mpFEneB+HM7zYPOxjyLdcm2yvMzTNM53k8ONii4HoFWJynBTQgj9R5gkLzTTK/Oz6aoUwxoZDupsTTZYsSX/DCwOOJtI2YiSZ14RhPIwNYvhoymK58ldFx0aaRZke4TGlWuH6l6i7DIosf1tqwsO0oBT/Bl5ZY+6Wk+8Nu+OKvgVzlLG6TsREt01qE0pf7CTHiWojDrv/ItIM81+Chypcvw0SOckbQX8Fxf1JzZ+hg71HZzGgeWG93HTlVYLZOaxT9LcaRrypS+jiaRPghIbBiEqKFTiV1Ux4cHQg3RJh3p39Sv+se+MAfM+sjRqrozUdQIkyL/+rs9HsjM8DYMjYYRh6y84Dqy5SiOgT8jg1ETj/dXZUb6XR2g8X9pyh69ofHj5fQg+ODD2z23PjXFEwD0uZRciBrsCC/9fkCpTVD8G5AVnabvQzljiq8WobBv07DCk7R8CSOS3Jxgxnrb0cakSVecljMtJjtTHxWziZdy16bKncgvh2a/7Jb1GXn3RQRapJ27C/hkEDoba5bFagf6Aint0dczgDmvIRpt5k+7A7GAsPojScoO6xHoqtJciGLDLFToHazhaOqpmh+yhjQDwvGVDaCM9MiAepbpPmIajXKv/UAxuFHGkjyVzZVdtU1xQMHl5Zb28Qug05I10WdVK7FHUbZ7sUUy9YCx1IsK6ohZsENcGFLmHpAmwe+kP/GN0fgg2VkY5DLnv3crf7Lppd8CU1miQ9+zrPW70aO3o4PBWncYzr4SMKIamDHxJ6eRiQPESrAuvonST8dKxSKMrv/Hi4UKBb8D65AtVyapM4w==
  template:
    metadata:
      creationTimestamp: null
      name: aws
      namespace: velero

