apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 5m
  chart:
    spec:
      chart: kasten-io
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: kasten/k10
        namespace: kasten-io
      interval: 1m
