apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-temporal-postgresql-0
  namespace: zentech
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
