apiVersion: v1
kind: Secret
metadata:
    name: temporal-postgresql
    namespace: zentech
stringData:
    postgres-password: ENC[AES256_GCM,data:WuZ02tOfgJIkGN6inUKeeyjDMTeLXb+KuEdIfnkm+XE=,iv:OEp+6nZJzXS3cZJB0bLspW6slbgPt5+Gg5SRYC2qgS8=,tag:8j8egodry4bzZAoweW2W2Q==,type:str]
    password: ENC[AES256_GCM,data:aZD0oIPN/UV4kabstvSajU5Rhjp+sLxcqtkw+UsK14Q=,iv:2Pp0SZLcONaN0d1vzqr/un4mMC/lqiCDX/EzGrTfQ+U=,tag:p8xNamlMqhCdeIirUZionA==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZ3JVVmd6SkxRN0kzTkxl
            QXhLM0daNFJrVnljNTE5KzJHRlpRM2JQd1ZzCi9scjR5c29kT1ZtQUdxTW9XaVNJ
            emczRUdtdEwyM2tWM2JjSVNRd25pZG8KLS0tIG9mN212Z2VxdkFXVXNHSnhZYWYx
            Y2FCcHd6ZXNtT2JpSlBzaHdnMUZnRkkKHs86SewNywPvy2pIiZgWonfewq7CRMV9
            5vHvFavqgDCv2yiy00ct6pEXCSc/iRwcpLFjCNJmulWbU2zt1os7Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T06:54:43Z"
    mac: ENC[AES256_GCM,data:m1RrHSnGB6XlnWCinkTW3ty8dqwlvQ68vts4mLMSgORBlFwcGfEd+bxbBtd8nJZeamrfQNizWK09gH800zA6NChvXVVN7TJl3h8AJ3TD666ZGvVXXt2RNocpwJ+xvcoV+OHTzIPsFxXIZnJtFaZ5LUNMQK8F7711x3lR7QlW7Kc=,iv:BCkuHS3DN+j6s15ASZxl2sN2mlJYvOGPFr2FZDaVybM=,tag:ncEWHM9v/Na6jA9C6Z48bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
