apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: mariadb-operator
      version: "25.x"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval:  1h0m0s
  values:
    image:
      repository: ghcr.io/mariadb-operator/mariadb-operator
      pullPolicy: IfNotPresent
      # tag: v0.0.20
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    webhook:
      certificate:
        certManager: false
      serviceMonitor:
        enabled: false
  

    
