repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/tarioch/flux-check-hook
    rev: v0.4.0
    hooks:
    -   id: check-flux-helm-values
