apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30m
  prune: true
  wait: true
  path: ./infrastructure/flux-monitoring/prometheus
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
