---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  interval: 5m0s
  prune: true
  dependsOn:
    - name: core
  path: ./clusters/home/policies
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-admission-controller
      namespace: kyverno
