apiVersion: v1
kind: Secret
metadata:
    name: mariadb
    namespace: default
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:nlMHusKfjZGHCYThsdXE5IBqdngizImCxhXLHkIDFkC5ymK0XJ8hhKHt7n4f03Lo,iv:VQ2aP9xcGlWSB/N9QlW6aT8qi3M3VYTksZYPXC7cPaA=,tag:k+ZUYhcO5pEz9F/yfwJt+Q==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:ydUtdmDxYv+UNk5vnSDzgXAziyzcSWnMBJQE4M19Ik0q9PQS/ucjr3lYA/luMrkV,iv:hbCgT6rjcU5YpVfBfBoovzW9rdMB0ei4b05JFq134lc=,tag:Hj7SePkJU3eK1dY3PA/Kxg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:kVCBrrOQd5V9ftrQWOMk1iVmBF4QRX9GU/HyR6aJdwIfB6hURn2GLyDkEwfJ7a9/,iv:JG5OC2RaWMSeiaAboEqHfVPDdtW4w+5HapfXnRYQgTQ=,tag:BM5f/m+H1rkuf60KK/V76g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVWRNbXZiaVhYb0hrWVdu
            MFpnUmg0SFg3b09tT1pGUjJmQ2ZwdVJkYlJZCm1jQkNGcUdWY3VtUXV0Y2dPb3Zw
            ekxvVHRhTU45MmVkUzJaclhNNXkrRk0KLS0tIDZnV3pRZGpVRzRyU1FzUDBuRnNJ
            RmhvSzJJUVYrdGw1TmZrUFRNaTNDWUkKPKMxwLnWrHr9sW9WPkeNua7pQ/Pdezlj
            DXxOQvQUWdh+CrqCp7+Ympo0oPPdDWrEVuyrLERi4NHH3eKPlR+YzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-12T22:03:39Z"
    mac: ENC[AES256_GCM,data:PnzQADAZ5ZkHOapuu6GDTeVMHFu0eQLlzZi2VhdegWlQMxwaWy499OdvRdx1fS3LyUhU+eVtXKP2t+URfpKvcn6BIsPGfNAdkvZ7EHOXpuHAeInVJgYl6fa1vZIB61EK4zwdO6NMRxSBqgWJjIqYF3ydpR4eD+yveiBFTjHeyoU=,iv:sQu4GvpEE7TT58lefjHrHFAqlpHF8ghvGjvjLYueCUY=,tag:FXFNLkgs34+A/V4qfqpwGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
