---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: developer-portfolio
    namespace: default
spec:
    interval: 5m
    chart:
        spec:
            chart: ./helm/developer-portfolio
            reconcileStrategy: Revision
            version: "0.1.5"
            sourceRef:
                kind: GitRepository
                name: flux-system
                namespace: flux-system
    values:
        image:
            repository: ghcr.io/pacholoamit/developer-portfolio
            pullPolicy: IfNotPresent
            tag: v0.1.2
        ingress:
            enabled: true
            annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/proxy-body-size: 999m
                gethomepage.dev/enabled: "true"
                gethomepage.dev/description: My personal developer portfolio
                gethomepage.dev/group: Apps/Services
                gethomepage.dev/icon: javascript.png
                gethomepage.dev/name: developer portfolio
                gethomepage.dev/pod-selector: app.kubernetes.io/name=developer-portfolio
            hosts:
                - host: www.pacholoamit.com
                  paths:
                      - path: /
                        pathType: Prefix

