apiVersion: v1
kind: Secret
metadata:
    name: paperclip-auth
    namespace: paperclip
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:OgVCq5u9mSvrwXsIom9YFcsVKFLvdCRZy2pzRwyzfvs3SmGWxXOIoTu5/qa6deFz3cmAiTTY3v8ZUDQTAG9iww==,iv:SlgVlK0HkB2NKDAqof2AHIFIL165JEQWABWSdU7dSMs=,tag:RVHgBKTjxVqT5FFWut8Daw==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTVdsVndyVXZqM3lwb1NL
            VHN4Q25BdGZJTWRlQitzeWNzeXNnQkdCUUhBCmhNNVZNanlnQmpNengwOTBkcndp
            MTVIZzIrbHkyQk5hOUg3SEExVWVaVFUKLS0tIERtLzB3aXVKU1M1bkoySVVXTU1H
            NWswK09kV1NwVTZQblo2YzZOdWlTcjQKMkLpwsImVtxh4k2hjOEatk7PuC9V/2jc
            Hzg9zDdK+NET1OoqEYUQcHqxcaeI0bzOsV2ofQTXh/rq34w+J5XFmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:22:40Z"
    mac: ENC[AES256_GCM,data:w3Pzgk1QgnzQYWt4GEZ8RHeOg2nSIK0pI6bomzcs5OJR1de7Hb4HD9u0jEv2IuMds13shIGKktD3XbiMjd44MUL2h39rgmNbCttf/RLh8rg9Yr8fZkAf1q2O0MYaPaEA93cEVgUb/buOo5wozy5+XErSIIJZTh+E+lUrWZNWUHs=,iv:Rh4zSFz5wMdORJZaz79V7C6GqlZWMQJNkiwUDn94pGU=,tag:QU0mJHSPwIRjzNarqV8OaQ==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperclip-api-keys
    namespace: paperclip
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:JvKK5onVn5PxE5wVJRGtBgVjc9DG1EEy3OLMjFU2hU/JGJwefHmlM145e85FHeMgQ9E1e6A0MCwXXGpVzj5fbbXVhg6m7rcUW7ZKcFAMhdypWgUmlwXzilz3WbYBbjBbhETKoULAu8nOsM4N,iv:h3e9dMhQarQASNCubx/0mnCyG+MnbIp5fu3Qr21fMuI=,tag:dOhd6f9JnYrUNsR5kGiLUQ==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTVdsVndyVXZqM3lwb1NL
            VHN4Q25BdGZJTWRlQitzeWNzeXNnQkdCUUhBCmhNNVZNanlnQmpNengwOTBkcndp
            MTVIZzIrbHkyQk5hOUg3SEExVWVaVFUKLS0tIERtLzB3aXVKU1M1bkoySVVXTU1H
            NWswK09kV1NwVTZQblo2YzZOdWlTcjQKMkLpwsImVtxh4k2hjOEatk7PuC9V/2jc
            Hzg9zDdK+NET1OoqEYUQcHqxcaeI0bzOsV2ofQTXh/rq34w+J5XFmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:22:40Z"
    mac: ENC[AES256_GCM,data:w3Pzgk1QgnzQYWt4GEZ8RHeOg2nSIK0pI6bomzcs5OJR1de7Hb4HD9u0jEv2IuMds13shIGKktD3XbiMjd44MUL2h39rgmNbCttf/RLh8rg9Yr8fZkAf1q2O0MYaPaEA93cEVgUb/buOo5wozy5+XErSIIJZTh+E+lUrWZNWUHs=,iv:Rh4zSFz5wMdORJZaz79V7C6GqlZWMQJNkiwUDn94pGU=,tag:QU0mJHSPwIRjzNarqV8OaQ==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
