apiVersion: v1
kind: Secret
metadata:
    name: paperclip-auth
    namespace: paperclip
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:vov9Z8tNCdDRh2o/r7e3saxyxnadeNcAljgUK/lyDCBtxRzJJSqAdR7GoQTy7JoBsnW4MNY2vjwJ8psizh82xQ==,iv:CXMzuQCvYFWVptd7GKHItlv7FgnXZ4/PdhA37HXCVrc=,tag:YbQBxHrxJM0S5CBNPItk+A==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVEsxampwWHBicWlQa2cx
            MnpZNnJKdVZuZFFqNDU4WERiWENsUjdpZmpJCmV5cUJCYlU1Q2lPNlVCUzZtMVRV
            b3pBNXp4UnJPditZT3pScUJQcURVNE0KLS0tIFkza1RCQSs3dUMrR1pYcjg4TWty
            c1RYN1oyRDYzWUxCU2N0QUcrUFFHV1UK24oU4FdFvUVIS147V9oKCKsz0oLRfplY
            eK9q1AZcs+8wCrfOoEdk2MXupWY7LrWUfkEID8hui54DNvkVqwtrtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T00:54:51Z"
    mac: ENC[AES256_GCM,data:49lMWCHir0ZqwKafMZbrhawO5rmycFh3Cniy+fYmikd4YScWo7cWrov8k/C+pdB93OzfWv+nRmfLZdCSlCyLFbRZfDk7oI4opMUCh+WYdycdI93Q+xOLAjGMZxxy7hDX/8avIiz2zefp7a/ExfW+TIKc8j9HTHBTY8yJo8EY3cs=,iv:HeajcDPbXbe71muxOR7/33CewR5+Twgl8pFv+G+xKWQ=,tag:BwIYcqpnDs3hBpH4lpyiqA==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperclip-claude-oauth
    namespace: paperclip
type: Opaque
stringData:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:m4Er752uuoBzhPpjOO2Zkl+Hz3Qq0M/IUr50IP3eDJTks4e/btn1rnkrVXKSyiL2y0zYJTPD9T/b53ePdFMyAXhZrsRtBMQNzP2dkFflR5QYr6EVn/ZEG2d5veSyb7WR7jhuhiiVbcCq/JKc,iv:pYDQH7B7a7FKV7fVxTymsirRnMoc5jNX+HRjh5f58cs=,tag:lzpSMTBKw2VWCh0u/GbBIQ==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVEsxampwWHBicWlQa2cx
            MnpZNnJKdVZuZFFqNDU4WERiWENsUjdpZmpJCmV5cUJCYlU1Q2lPNlVCUzZtMVRV
            b3pBNXp4UnJPditZT3pScUJQcURVNE0KLS0tIFkza1RCQSs3dUMrR1pYcjg4TWty
            c1RYN1oyRDYzWUxCU2N0QUcrUFFHV1UK24oU4FdFvUVIS147V9oKCKsz0oLRfplY
            eK9q1AZcs+8wCrfOoEdk2MXupWY7LrWUfkEID8hui54DNvkVqwtrtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T00:54:51Z"
    mac: ENC[AES256_GCM,data:49lMWCHir0ZqwKafMZbrhawO5rmycFh3Cniy+fYmikd4YScWo7cWrov8k/C+pdB93OzfWv+nRmfLZdCSlCyLFbRZfDk7oI4opMUCh+WYdycdI93Q+xOLAjGMZxxy7hDX/8avIiz2zefp7a/ExfW+TIKc8j9HTHBTY8yJo8EY3cs=,iv:HeajcDPbXbe71muxOR7/33CewR5+Twgl8pFv+G+xKWQ=,tag:BwIYcqpnDs3hBpH4lpyiqA==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperclip-oauth-credentials
    namespace: paperclip
type: Opaque
stringData:
    PAPERCLIP_OAUTH_CREDENTIALS: ENC[AES256_GCM,data:7df8YkIHXa7HxbvL4IOPqoH7lzQlgCp6RNQdlRsGYWWq+RZss/04eedbNoQildsoghrnE0m1nHpUsoYPsOjB5ULJzc16QkRMs3YkV007WXI6DaSol4VltISnb6ngM09zkzA/tZDrdIFtLlYgIDhBBC4D7zL8AxJSKNd58gs=,iv:cmlFObnZbaT2hGofj6IcvrYVlAEpr/DWE6Tks96+hWA=,tag:R4XrVh0akkx1tF0ehF4/PA==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVEsxampwWHBicWlQa2cx
            MnpZNnJKdVZuZFFqNDU4WERiWENsUjdpZmpJCmV5cUJCYlU1Q2lPNlVCUzZtMVRV
            b3pBNXp4UnJPditZT3pScUJQcURVNE0KLS0tIFkza1RCQSs3dUMrR1pYcjg4TWty
            c1RYN1oyRDYzWUxCU2N0QUcrUFFHV1UK24oU4FdFvUVIS147V9oKCKsz0oLRfplY
            eK9q1AZcs+8wCrfOoEdk2MXupWY7LrWUfkEID8hui54DNvkVqwtrtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T00:54:51Z"
    mac: ENC[AES256_GCM,data:49lMWCHir0ZqwKafMZbrhawO5rmycFh3Cniy+fYmikd4YScWo7cWrov8k/C+pdB93OzfWv+nRmfLZdCSlCyLFbRZfDk7oI4opMUCh+WYdycdI93Q+xOLAjGMZxxy7hDX/8avIiz2zefp7a/ExfW+TIKc8j9HTHBTY8yJo8EY3cs=,iv:HeajcDPbXbe71muxOR7/33CewR5+Twgl8pFv+G+xKWQ=,tag:BwIYcqpnDs3hBpH4lpyiqA==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
