apiVersion: v1
kind: Secret
metadata:
    name: paperclip-auth
    namespace: paperclip
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:tRQQzUdkJa24OU9CaJ3THjK4klFZdYdXKi6y5ywR80Zsyav4U8wCT2+7m0DuBYPGcAd7V+9acd/OX3NAS1rvCw==,iv:5dYR+N/dUuafF4VhrF6pZvRRMJpJcUR+eD5bCTuXqkM=,tag:EcF4YFt/XcJluRKtuMUWxg==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTUlRNXZKUWcwVU93SnFq
            bkRvQnhqUlBVR21CcitKek9pMGprRi9aeFJvClZwWHpxT3VsK1grdkIwaERFMHd1
            WWdyaUQ2amhST21sOWRBVjExWk9HZUkKLS0tIFFBeFJnYTFsVTNpQXZJQk16blRp
            cDF6THdYZCs4eW85aHpvdllpZHRtY28KhAOmz7rkTOsAJQ/kxoPm3/Wgc8xWNDlj
            E7CWaLmowE1WswULtxsqDASOb9/YQFI6GgVLwAx0pHBYs2nE221r/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T16:25:18Z"
    mac: ENC[AES256_GCM,data://4c0mIYgcn8HIwAk6okfXBFlvAylIfsi78ZNGkfSJQCtyh041BjsA9mfLjSlI4cdhFnPNuXceGvmUz1QFhoAEUsgcow+VKXzCuP7qkH9NUPk8O9+UkSBBD3S4vS0/xUHOptu/wN4AkM+7i2yPi3d87f/f+Cgx4U5zD6RJ0+1Ws=,iv:hCspnj9yma1c9JPk5+azty1iUOzJ4xe+frY+MgfwyPE=,tag:ESSyNLZmgp91WGk25nEw1Q==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperclip-claude-oauth
    namespace: paperclip
type: Opaque
stringData:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:/edayc11aTrTyXdU7F2FknMthaA/sBiPvr04X0acQ/1Hg/3jNAWgUABVvYGrkBgJQpfIznr1D+Xpxm9n7ItSOBTq0NXrkeevBoYZJZTjvdOWw4m51kfK3nyJQ70xRkUR10zjNgXcdkmWaodj,iv:9wVVP3LCwQi9GExPibugW1UGArO/HCEWfg+aG8vZBQI=,tag:EWAQLxTwoDkMb5FHo9nvDQ==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTUlRNXZKUWcwVU93SnFq
            bkRvQnhqUlBVR21CcitKek9pMGprRi9aeFJvClZwWHpxT3VsK1grdkIwaERFMHd1
            WWdyaUQ2amhST21sOWRBVjExWk9HZUkKLS0tIFFBeFJnYTFsVTNpQXZJQk16blRp
            cDF6THdYZCs4eW85aHpvdllpZHRtY28KhAOmz7rkTOsAJQ/kxoPm3/Wgc8xWNDlj
            E7CWaLmowE1WswULtxsqDASOb9/YQFI6GgVLwAx0pHBYs2nE221r/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T16:25:18Z"
    mac: ENC[AES256_GCM,data://4c0mIYgcn8HIwAk6okfXBFlvAylIfsi78ZNGkfSJQCtyh041BjsA9mfLjSlI4cdhFnPNuXceGvmUz1QFhoAEUsgcow+VKXzCuP7qkH9NUPk8O9+UkSBBD3S4vS0/xUHOptu/wN4AkM+7i2yPi3d87f/f+Cgx4U5zD6RJ0+1Ws=,iv:hCspnj9yma1c9JPk5+azty1iUOzJ4xe+frY+MgfwyPE=,tag:ESSyNLZmgp91WGk25nEw1Q==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
