# LINK TO INSPIRATION
# https://github.dev/Michaelpalacce/HomeLab
# Search for SOPS implementation
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: focalboard
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: focalboard
      version: "1.x.x"
      sourceRef:
        kind: HelmRepository
        name: mattermost
        namespace: default
      interval: 1m
  values:

    image:
      repository: mattermost/focalboard
      tag: 0.9.2
      pullPolicy: IfNotPresent
      
    persistence:      
      enabled: true
      accessMode: ReadWriteMany
      size: 5Gi
      storageClass: longhorn

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: focalboard.pacholoamit.com
          paths:
            - path: /
              backend:
                serviceName: focalboard
                servicePort: 80

    
