apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: n8n
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: open-8gears
        namespace: default
      interval: 1m
  values:
    image:
      repository: n8nio/n8n
      tag: 1.18.0
      pullPolicy: IfNotPresent
    config:
      database:
        type: sqlite
    persistence:
      enabled: true
      type: dynamic
      storageClassName: longhorn
      accessModes:
        - ReadWriteMany
      size: 3Gi
    extraEnv:
      WEBHOOK_TUNNEL_URL: https://n8n.pacholoamit.com
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Open source workflow automation tool
        gethomepage.dev/group: Apps/Services
        gethomepage.dev/icon: n8n.png
        gethomepage.dev/name: n8n
      hosts:
        - host: n8n.pacholoamit.com
          paths:
            - /