apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: default
spec:
  encryptedData:
    address: AgCxE87P1j1p2HH9EZLnDfpgFzsx/eRe7m3z+y15jkRhxcJ/+zG3M9V+v/iZ9lXeu/OmZ3NyPW8qk0kpDEwwHAYGFAc4j/+nYtgiNWa7hvtUsklEfiTyfVbg8JQCL6MukD2Xt7sHH+de7p9OyYqR+jci1VDyfL+9POHsvD7LBG5okk9SkM91Ap1O+uTT2/y1ZnW4qOu89E0YX3AdA9ZgDlzwgfceKEk3y8PdnUirOxk+TMjFAAdJXl9zmOMAegn0KKhU3SSzoMHyxlb01IXVH3erj6LobwgAWL24kpXfuZmhrSgtkBv3CArsR5RQ7lHP0JwH5zlSH9gew8VXtqFkoWJQJf5GPuNMw5OoNe1UROAIpaQ+ngWDGR1ENUBRgIDCJ+eHcXUGX4oGDvRuWDzAtSbvNelGcSM1QlHc2tnbjApEZ2ZyCSnMnRDWg127rqJHC5lWo+UmfnpTk0kRoVlgOzQVqZmaU6NhA2MYQ6BmXfjoKUBRJ2bv55k2hOwmU9QmD1VsO5Kie8KKVwx34F48/0DGbe+aowhvB81vaS+ufYl2ThBo9U9cMoUL5eYa5XFPzEwIw1sjXLgXHl36gwozGjCRmrplPYSTDrSiuf/NacUOPEmLrO0s+fTXUEpiKw5cQZRjsZoaP+9fmkL8s8hY2Gi30af7+jUfmFeTbyleCsLM7RUiy6SdDM8KpdNqwhUGAGHM1vJ1X3meS5zgWHl8zl1LoiQyWEPj9jkhwzkw88xdZpDmmTTRGghwLWxIi47JnSIXZGQKueCnWt2X/KzDvJ61TBHLZQfbx5dSIjcs2oleGiQ=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: default

