apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBqroglZ7hn5rr/fPEW+EQgptW4MYpIYOnSTk0Y4ZCaBNkrCeM0Z0Gq6KGmxd8D93pUU5x08z66BpONTFmN0dPlMUuHLoBnJPqm4l75ukucBEnppT3XqC+9/XweAyKbj5JyKKU2R8HcXrb9UsiijeIjCXDYvMSv29i9vFhmzafAi3uujE/rqiWwnN8qxHQNErd1fS7awSM13rsjpdcFngBOsYIW9wVZIuQv5jYKAR9QpJihOq+Clndu48g2AmUFSVcycKhi9E5/NjzzYKpal6fsJ3bFJbBWshLXTBXEfqr9w+ch7zbTpS+gFCxjk3Pga19mjCYoovEx4ybQ5m2yNb0sE0xc8dqgSqIkvonhpFcckzvPPWC8ZrboBpNquPQg81cr1elth0bffC/xrDRCbvH7LguQldbN6gLFFG2GmHVzRvSTxKbze84YgAeptJZrSog1eVHHpn8eADUNhOU7sQdHdFze/RJbXR54jCfTuPnoGuCytY53LJgasT7FBUV2FRvnH11WDNODkQXhmnvMFvmUkhaBaLvOtRnkuTKr5qk8Ls1BC35MMdLYsxzL0k25xPtqKPCD6Fyiz5FficR47MR7r4hWoEqo7kOCsr1qKqKzkGGqeSECZ1S7VnYKAnSxzg6HVKJbskBcdRtLRbhL6mCiFBSVPn5yb0sIi5h6C2WZq/xALg31NsDn2mu7YLx8iQphBbT1dToRBDHlwubCXH0pMYqjA/VAsJTmnzDcBpH9vc3o6f9KxOp8CVbBs5SOoCvans5JZl/mAbYzgQxO/db7AS5ltJVyei95NVFvXAuwyHs=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
