apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: monitoring
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 30m
  prune: true
  wait: true
  path: ./manifests/monitoring/monitoring-config
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
