apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
