apiVersion: v1
kind: Service
metadata:
  name: termix
spec:
  selector:
    app: termix
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: termix
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Web SSH & remote desktop manager
    gethomepage.dev/group: Apps/Services
    gethomepage.dev/icon: termix
    gethomepage.dev/name: Termix
    gethomepage.dev/pod-selector: app=termix
    gethomepage.dev/weight: "1"
    glance/name: "Termix"
    glance/icon: "di:termix"
spec:
  ingressClassName: nginx
  rules:
    - host: ssh.pacholoamit.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: termix
                port:
                  number: 8080
