apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eraser
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eraser
      version: "1.3.x"
      sourceRef:
        kind: HelmRepository
        name: eraser
        namespace: kube-system
      interval: 1m
