apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: eraser
  namespace: eraser-system
spec:
  interval: 5m
  install:
      createNamespace: true
  chart:
    spec:
      chart: eraser
      version: "v1.3.0-beta.0"
      sourceRef:
        kind: HelmRepository
        name: eraser
        namespace: flux-system
      interval: 1m
