apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: mariadb
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  requeueInterval: 30s
  retryInterval: 5s