apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx
  - longhorn
  - system-upgrade  
  - kured # Restart kubernetes nodes
  - rancher
  - node-problem-detector #   Detects if a node has been affected by an issue such as faulty hardware or kernel deadlocks, preventing scheduling.
  # - reloader # Reloads config maps
  # - rook-cluster
  # - velero
