apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx
  - longhorn
  - kured 
  - rancher 
  - node-problem-detector 
  # - system-upgrade  # Enable for upgrades
  
  