apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx
  - longhorn
  - velero
  - kured
  - eraser # Erases irrelevant container images
  - reloader # Reloads config maps