apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: default
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: mariadb
      version: "14.1.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1m
  values:
    auth:
      username: pacholoamit
      database: mariadb
      existingSecret: mariadb
    primary:
      persistence: 
        enabled: true
        existingClaim: data-mariadb-0
      readinessProbe:
        enabled: false
      livenessProbe:
        enabled: false
      startupProbe:
        enabled: false