apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: "11.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    architecture: standalone
    auth:
      existingSecret: mariadb
      username: mariadb
      database: mariadb
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        accessModes:
          - ReadWriteMany
        size: 8Gi
