apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 30m
  prune: true
  wait: true
  path: ./manifests/monitoring/loki-stack
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
