apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: mysql
      version: "9.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1m
  values:
    auth:
      username: pacholoamit
      database: mysql
      existingSecret: mysql
    primary:
      startupProbe:
        enabled: false
      readinessProbe:
        enabled: false
      livenessProbe:
        enabled: false
    persistence: 
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteMany
      size: 8Gi