apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - repository.yaml
  - secret.yaml
  - service.yaml
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  dependsOn:
    - name: sealed-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  wait: true
  path: ./clusters/home/sealed-secrets
  sourceRef:
    kind: GitRepository
    name: sealed-secrets
    namespace: flux-system
