apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgAwKiFSw784P5C04XUWHcMEGatwPdZCAguj81tsxgkKU7D9y0xN3mT075pOnv4z8rcclS09wIHRmNyj3fjHdW2k3Ej4Lf12RRu7IhXj1zBHje7gcYnN8G8tfopFMf6RpHNEw3cy9DcnOUbTM5KUACCt+QdajWFOE9JUOeCDqHUv1LzFBdj6eCBhsVfkD9kCXSf0p87sQUi8ouZQn+keuChtD06TXA0OJoL7EsEdD4ck68UO4mWfje/uG4fB1E4q3BnqjN96zxHw2Q2oik84qGLJqnbBD00UA5VrB81l5JFMUJpIf/lCWodGiwWuaDmyv0rF3Qrr7lO62rbWFnsnlEmj2j691Ti2iSIw6oq26Qy+ahZVY14cKxZG/CD+d3KD7P+SlG+lF0Qg/nNtRKj/jpraTm9OTinC+3cgXksoshAhP8khwpKJbLaZIcpV6zm17oApUTphkURO6/aey2lz+q/xE6mU46OLtzHy57aigjtSgpLixu4vAJzXw6a6UrCveI4fr2/98z/skRz6+ISB89sNEm0iT67IFg14enRdzV9C03NqoOatC3n48obCpX3n+xqbqdDgEEMLfZJ8K2HiGEMd8ZbAfAWS907KiETNc7DqS6sTiwghzJA15VAhw58v5OG0d6qzESiaPSGaKPlSArm+GmQrN26U4Es1c6zpbxo1oapjSg4HYU/uu6m6xcCVVJg3y8Htx5mFjB9dStogUrHCV4x06tSVRiaZsyIiIQ1b32F746RX91vzAPTCacB60ULlXQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system

