apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    password: AgAkhuKjWv3E53SH9itP0VlenjRlkly9fcnGUOkJ+NUBLDd6tAgWW+vhBFSPCGrkatXOQFR3SpE3HT4wYzBONrHcCSTKuHCEnCXj2jDaOkHKSvKOImeUAn47zQeqN4jwCtU1oeTjLl32+o0cVOZ/4H8KnivMvF9mRHXKk0XfRQZYIn5dUBVDFiBUKZMRcXctBuRN+GjI8XXgcvoKM2+BP+rOoRYlElhUVJZ0mvudf1LLMZu3/o9ly1oSQxKXChQRFdYYI2LvJ+tVEENK/yJdESe8tJqcVtLN6DphEkkk9P1zAJkGGKqm4tWXD2cYL96JbBfD1x30J59VRIxZ0DtEPB+1K+jHgJP893+C2eCrddHXAK6W3C0b/4379aXmwnxjqb6OUjpIhvqpnlzYmqi80PFNQmuiLACXaNHWr5t97Jd4lqk5Sw1EE+K7fkV+SwbI2xXYm/7y+4jpPvFaq/83GJCFYTM8eGuVtRVgBZ4XFz/2SVo32VajgfQBUqaoGIeu+R5NfdfPAST25PVX0iXrDlE0KVigqEoVpHo6kSbWGoXe1JRdt8y3Mswl8btod2sS0VFji1/+hrB9l1zF8Wyz6BymdQTWGAtUEVsid3dsADyLiJjXYfq6Ue1lqZfs2XXHc6H4chrDG6dpowQQlypxMiafMQFSh/nWP6nW/81f/j/fuo3LJPvaagwGXV2UYvdn6ufe1SZpT21V9ZizIt6TfVnf1TBkvhU3bNFE/nYaUaY=
    user: AgCVHvHD8Q9GB0ocojYiqGj5qDBWRaOFwEqWwWawAneG+H4IJGp6GMXKdeP92o+Ih7Q/tZr2I2dMSlCLjuIIvxFWes8iLU7eBd/hcCG+NsCOMo5piVUQIs6LxUjFwLT+sO1E2Nr+viEpa+1jLcWvP0fVulmCMgkhUEDGKHhXnl2QihTyy0ZcwFLoUfdXcaoAZAjrrIlUHEOGloAvG7azlrES4wEKwVYIJp2Izizg/pUpz8Cwg0zWn0D7IvsvCudz7QdqdCux7zrWKeHBwXEN+9qF2Zes4xZXRCa8C3cyrAKcRzk4a8zGPSDU6jB3Mjz0ah7s+22wUPw3HMJPoHZrtijyk4GX6LIH8cq4orUzRonanhZFO1nJScsJ6cix99m3Hfsvk+t6hq6O5JhJn3yBkXXrVi88tWzSHIPBI+Xh+y3ZJm10Jvc/stHn+UBZZkh2yZw8hlG0zbq/uLsf1DoC3rTRdRUXaVfLISzsZbdIMZttZHzNhBSGY7X71zG2T//z6uElc07EgHLTY88eLttCU/Gpxhj2pbFQuy4Qk8zqU1NFIxPD5Gx+RnPa9a9owfze/oYEaGhGd/Yuxyq+IQ0nQ0sS6+J+6wi1AHDSEh9nm49KV5GHqS4OqTD8k/JMJgZBz4nLY4vyUmS28fwbbXDKzHaZHdISYjcPG8P3LcLCYEpcXg/juXRg3xJHA2xVCcEfvscjmM3VTgvrWa8Saw==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system

