apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vikunja
      version: "0.3.x"
      sourceRef:
        kind: HelmRepository
        name: vikunja
        namespace: default
      interval: 1m
  values:
    api:
      enabled: true
      persistence:
        data:
          enabled: true
          accessMode: ReadWriteMany
          size: 5Gi
          storageClass: longhorn
      ingress:
        main:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: vikunja.pacholoamit.com
              paths:
                - "/api/v1"
      configMaps:
        config:
          enabled: true
          data:
            config.yml: |
              service:
                frontendUrl: http://vikunja.local
                enableregistration: false
      env:
        VIKUNJA_DATABASE_TYPE: "postgres"
        VIKUNJA_DATABASE_USER: "vikunja"
        VIKUNJA_DATABASE_PASSWORD: "vikunja"
        VIKUNJA_DATABASE_NAME: "vikunja"
    frontend:
      enabled: true
      env:
        VIKUNJA_API_URL: "https://vikunja.pacholoamit.com/api/v1"
      ingress:
        main:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: vikunja.pacholoamit.com
              paths:
                - "/"
      
