apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter-crd
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/kubernetes-csi/external-snapshotter
  ref:
    tag: v6.2.2
