apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: snapshot-controller
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: kube-system
      interval: 1m
  values:
    image:
      tag: v5.0.1 # Do not change, this is for longhorn compatibility
