apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: snapshot-controller
      version: "1.8.x"
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: kube-system
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
