apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: netdata
      version: "3.7.x"
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 999m
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Monitor everything in real time
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/icon: netdata.png
        gethomepage.dev/name: Netdata
        gethomepage.dev/weight: "1"
      path: /
      pathType: Prefix
      hosts:
        - netdata.pacholoamit.com