apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC7QvUwsimpWVoClaTyj9b7VwTlpSPPEsdBxbxv21lsTeuC03nD3ug2xYQ1TQC8KUJE8zw/+HihK/HwMfYdoomJh/zrFisdRHURpqHdshU9yGwiGFCDyFAY1vTHX13JCN/wD7aH1Q6gEFLj1Ubetnv0LydOH2cOMwS7stBJUc64OSRHRkAnSzZqu3Hv6F9s5c8+9OQ9CzACBb4liWGIdm1MJSqhCUm7JtOxWXKBRRPdjaa5k7TH6g8bESFA+eE2P3PZ6N539pN150QV+CuVaqKgo8xeVTiyTDxP25csZUsQWHxZh8u7OIfaXpgpvij2kPDZcgDOESSZxP+d6fM6jjie06tRQb9yb5kmCF3Rig78K9LcsG3LmUXsWLbrfRgMDCU8OHSWcS3sMRoGystrSwQxM9vFF+SbtWsRJCw1p6PTb9SbmuOVHrbbhklmUQfD7T8DTL6UPhzFr62xnwiGD0yxVVE3puN74ilb7soNt+j5q81Hi9iJtZPj1BRmms1OCiEk5CrWcDwgCugZNrOEbH+7NwigiOc3AAGHdvsPZj+BM2egPvOrCemzBperEzrf3PFE1gpZvUY4FIp3yAWA4hiA/tj9WJs0YOtFs1Gmqb6RjBvTG0TP4WQfA7Cwdxd0MUYk7nxYiYJts7hkddgjvbxuzbj8tE9cdxN3GLdveF7Ug6CvQDSDwNVqueqI41jw0Qq67JLpVxQwStKP9mv9kfkpRCuBBS944+5vjKIf/HI=
    admin-user: AgAdpjWgUHdsW7VU0FM7NOmJXbvA7OeleSMQApa8v2C+2P3ijlZ0qwafzJ1eRNeBWL0UyyjJHcneGuF0PISGeR50y/UVJR/USNPR1TUp05EqJgYDVRY0oBH3evk2RIGnZDpkWfo779nOQppg/Ji1DadnJb/mOs5TcXKyfvBqH6kdptCc+aqN1NIIQW65CkoKRhSo3Tgs5groIMALX4vzx8ANldbyTxtKUj4BN7GYbNxstL/4AmpiyoN0KrJqzZLLdxqTEZONTgG66TvQupyZVRteUTW6HDt1Q+Hu/yR1hv7I0J1C5W8WGN2c3IiwbC63+Kdp42IzTJihXvPgK6NVnOfO8OpFX1auiYIiBhr/vIVR3cQeUuZEqzp7xuwESau1ZmkJAIwgp+EeYnif5NCSH92Mpv/1mTGSbJWdOZE/yi6srUKU89T878qD5/TNzR1ldoeDjwFWmdAxvZCGdA1L0K64rDz12DF0RGtzTGal7we+1S1xZkIr1RmiDnHHxlZwyWQgpQ5WJV1MiQftCyxolHmxMMQ0FMfR+ijjIuWSBzVE31u1NKBZHVdCKvhEqyniv1lcp9jZIKVB6sQ494AnKJZiuPx/2t/1PmOceV3KEmLyiGtXPBPljnZmXQsFnc2d5SiMTNpIxvHu9FNhLui4N+XzFR+W6Uz/V3fzqAt3W38vVoJsV5dHyQi+fl7x2toAGJZnm4+4ShDAA/gzPw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
