apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: reactiveresume
    namespace: {{ $.Release.Namespace }}
    annotations:
        kubernetes.io/ingress.class: nginx
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Self hosted resume builder and hosting platform
        gethomepage.dev/group: Apps/Services
        gethomepage.dev/icon: https://rxresu.me/images/logos/logo.svg
        gethomepage.dev/name: Reactive Resume
spec:
    rules:
        - host: resume.pacholoamit.com
          http:
            paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: reactiveresume
                        port:
                            number: 3000
        - host: resume-api.pacholoamit.com
          http:
            paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: reactiveresume
                        port:
                            number: 3100