apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 168h # 7 days
  chart:
    spec:
      chart: longhorn
      version: "1.10.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  values:
    persistence:
      defaultClass: false
      defaultDataLocality: best-effort
    defaultSettings:
      backupTarget: s3://velero-k3s-cluster-backups@ap-southeast-1/longhorn-backups
      backupTargetCredentialSecret: longhorn-aws-credentials
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      detachManuallyAttachedVolumesWhenCordoned: true
      guaranteedInstanceManagerCPU: "35"
      v2DataEngine: false
      v1DataEngine: true
      orphanAutoDeletion: true
      rwxVolumeFastFailover: true
      autoCleanupSnapshotWhenDeleteBackup: true
      restoreVolumeRecurringJobs: true