apiVersion: v1
stringData:
    auth: ENC[AES256_GCM,data:VOtqli095JiXfMS4oKWjbxUuSsB4zqtC80GvqaA5V/cLuSNXsh0SkjPNMrH8ez8hgg==,iv:1IAgOpzHl0TDfeqvNn9ujP1xOQ1/fHmEaCaKSEqXAjc=,tag:7x3/4lGwPxZTlHrCoPyTOA==,type:str]
kind: Secret
metadata:
    name: basic-auth-longhorn
    namespace: longhorn-system
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WG5jeUZSK1Q4RUlCMVdm
            U2VNOHNNcHZueXh0TnBwQlBONE1nVWhsMW1VCnE2SDFDelAzRkNPQ0JScStxS0ZH
            VEpRaFJ3bHFLQ1JwMU51eU1aYUN5RFkKLS0tIE9YcHVHUTdWT3dxbjdNNkxrZlIx
            NFlkTStGWnJiMDE2L0YxMUVPNGp3ejgK4fWwsasehFQY63OFj5UVEAjKLd5gMXHB
            aRkfXIxUJvtBppgY6WRYllS06sCtV0Uk2fIj9h9vtV+WOs/RRcm6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T21:19:59Z"
    mac: ENC[AES256_GCM,data:fbY+93PRtaNSKeJG0cGn+W1xzT7w95tIXFK8ttCvnuxu0HNiaxgQFIf6nlDc93ywmIcH9A8hOHY+dSH3HS0SA4ifThYQVU88smiNmaHU7lvqKCPCL94geMk1uCnXZfZg7ich97E5xnr6g8Jxp8c3aKxL9FsviJWk0WgcujUHKSo=,iv:x8zBF6JCu1SxTD6EWvG3p+aoi3B3Z4uo+ibUMEEjMFc=,tag:eAbsiG0xaj8i5yKlmqLDEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WqtCb1JRZCJVP7pajgCNcAORZ2E=,iv:hf2KMa7nNCncBmSu+HpPCP3I/H9rmYt4PsQlcWU3I98=,tag:kXAwwrlkaNyVXjMhCURhxQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VjTEGIqJL7pNs88+BtnbDUVuSBnUhjC8eMsI1Hc6HifHFlB0fgi/9Q==,iv:PWFFDzNRIv2cAWDMNVtMICtP2VRVh2sSNmqQe0IJsdE=,tag:LKeH9X8MpLGBxB1DQ1Z5FQ==,type:str]
kind: Secret
metadata:
    name: longhorn-aws-credentials
    namespace: longhorn-system
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WG5jeUZSK1Q4RUlCMVdm
            U2VNOHNNcHZueXh0TnBwQlBONE1nVWhsMW1VCnE2SDFDelAzRkNPQ0JScStxS0ZH
            VEpRaFJ3bHFLQ1JwMU51eU1aYUN5RFkKLS0tIE9YcHVHUTdWT3dxbjdNNkxrZlIx
            NFlkTStGWnJiMDE2L0YxMUVPNGp3ejgK4fWwsasehFQY63OFj5UVEAjKLd5gMXHB
            aRkfXIxUJvtBppgY6WRYllS06sCtV0Uk2fIj9h9vtV+WOs/RRcm6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T21:19:59Z"
    mac: ENC[AES256_GCM,data:fbY+93PRtaNSKeJG0cGn+W1xzT7w95tIXFK8ttCvnuxu0HNiaxgQFIf6nlDc93ywmIcH9A8hOHY+dSH3HS0SA4ifThYQVU88smiNmaHU7lvqKCPCL94geMk1uCnXZfZg7ich97E5xnr6g8Jxp8c3aKxL9FsviJWk0WgcujUHKSo=,iv:x8zBF6JCu1SxTD6EWvG3p+aoi3B3Z4uo+ibUMEEjMFc=,tag:eAbsiG0xaj8i5yKlmqLDEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
