apiVersion: v1
stringData:
    auth: ENC[AES256_GCM,data:nrfAGBCXEbbnStydHkmRjiUVLCwmTZzfM++NjRrjI2N1TfEKq9ZUoaaM4tpamYSeiSJbITwNJWJlQnnwRDSwKI0F1dg=,iv:sKhiRA92JaFk1KVrCX+V23d6+ke/tAl1E5isRzTfkvM=,tag:05rN9gpRSEfmDljJ9g50zA==,type:str]
kind: Secret
metadata:
    name: basic-auth-longhorn
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WG5jeUZSK1Q4RUlCMVdm
            U2VNOHNNcHZueXh0TnBwQlBONE1nVWhsMW1VCnE2SDFDelAzRkNPQ0JScStxS0ZH
            VEpRaFJ3bHFLQ1JwMU51eU1aYUN5RFkKLS0tIE9YcHVHUTdWT3dxbjdNNkxrZlIx
            NFlkTStGWnJiMDE2L0YxMUVPNGp3ejgK4fWwsasehFQY63OFj5UVEAjKLd5gMXHB
            aRkfXIxUJvtBppgY6WRYllS06sCtV0Uk2fIj9h9vtV+WOs/RRcm6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T23:18:07Z"
    mac: ENC[AES256_GCM,data:xCBDtJwYIkxERT53eGhrIhMCi2ilBfl73GqqhxQ2CPBILyGn7eyoHFSFKYC8dfmQ0LV/KdZ2th4cKiTp5wYuFbi5lMCvR9yzhfpEH1u8kJ/RD2ImJZjca/351gjFb7fU8DQ1MI/r45R6xqYJo6/TPNwZBEC4M63VdwkFxHb0iE4=,iv:TnYbDm7PA3p4ObMdSvDzcdKVmF5OmAfwRN2/L+8KkNA=,tag:pGldbvEsfHybFgJXn2myaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
