apiVersion: v1
stringData:
    auth: ENC[AES256_GCM,data:nrfAGBCXEbbnStydHkmRjiUVLCwmTZzfM++NjRrjI2N1TfEKq9ZUoaaM4tpamYSeiSJbITwNJWJlQnnwRDSwKI0F1dg=,iv:sKhiRA92JaFk1KVrCX+V23d6+ke/tAl1E5isRzTfkvM=,tag:05rN9gpRSEfmDljJ9g50zA==,type:str]
kind: Secret
metadata:
    name: basic-auth-longhorn
    namespace: longhorn-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WG5jeUZSK1Q4RUlCMVdm
            U2VNOHNNcHZueXh0TnBwQlBONE1nVWhsMW1VCnE2SDFDelAzRkNPQ0JScStxS0ZH
            VEpRaFJ3bHFLQ1JwMU51eU1aYUN5RFkKLS0tIE9YcHVHUTdWT3dxbjdNNkxrZlIx
            NFlkTStGWnJiMDE2L0YxMUVPNGp3ejgK4fWwsasehFQY63OFj5UVEAjKLd5gMXHB
            aRkfXIxUJvtBppgY6WRYllS06sCtV0Uk2fIj9h9vtV+WOs/RRcm6yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T23:21:00Z"
    mac: ENC[AES256_GCM,data:L0QAyVDhVmLXVoEGmVzRHWp5hbUW89pKzLcnK/b/By6pN6COqESWeQd/deqlpwKG+K8bvi1tdm+1xagedg+Y6/jQgKfi8VT2AcihgeCeyyKZLIwa7UF8tdRS2r6Cr7mYl+aU1YyrXR+AZO4Qcu/nQfK6eLLgNyMLi2FlUP7I/z4=,iv:i1jdiAFVa+sd63T/1fHAx44KrQ/ktHBOS0s2vMo1IPA=,tag:RjzHUfTtMUCkqrGNSamtTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
