apiVersion: v1
stringData:
    auth: ENC[AES256_GCM,data:in2mY7VzGF2tKFnLPcsoBEEnGRNQaEzgBmJvGXHd32o4tTrwqs61x4tjcaBu1a5oXgoaYPYYPNtiZ8Q+NdHoNvgihTQ=,iv:LXzfTIeIPyFIEM9RZCem3Ao61ZCm+Kzx+hubWCjewDw=,tag:1AOlcpTrQ4pCuTRXwIcUiA==,type:str]
kind: Secret
metadata:
    name: basic-auth-longhorn
    namespace: longhorn-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdG1MVVdTMGJjWkNVdzNH
            Kys1cFAwMFlwNnBFWjk3dTJacWxmdllOYWo4CmV5eTYvMm9vN20vR0pYSXl5bDJN
            bjdBTDhzTDkxSXE4UWg1ZkQ4OVdEQlUKLS0tIGlqcVJnK3VmdXR1LzZoV1M4VEhp
            M3YrUkE4VlNrek9OUzI4d1FTdFF0RGMK86C6MmhHXwoN4n+ttFcgEtnGIuynR7S8
            PTea950q+3SyheZUDzsTiEifcDpwJC9ee0jz/LRBkWT8CA5DkGd1rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T22:46:27Z"
    mac: ENC[AES256_GCM,data:K2wDm7ZIGeJaLXa2RDj2cT2vnPAARP9hBu3MEi73BZ7XYNXsjheySmBYV7qDm58UCxwWSNPYNFjNglnEPZloraU+6gHXG8GJiERgiDaCLMJpb+o32BqbEB1DLfsB1nlMKWOkGlzr9S2dB7tnDBkZUaHhO/lvYtgpx+iMwi3vLZc=,iv:6BVHGhvcdFwzDBoxgtDGq5dmh2FBTRmdV/woM7EQ6V8=,tag:yaCRRiMiyl02FcgwsJGXeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
