apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: s3://velero-k3s-cluster-backups@us-east-1/longhorn-backups
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: longhorn-aws-credentials