apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
