apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: "5.3.x"
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: kube-reboot
      interval: 1m
