apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: "5.4.x"
      sourceRef:
        kind: HelmRepository
        name: kube-reboot
        namespace: kube-system
      interval: 1m
