apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:2NAvzn084N8IRfHY8yfYezngyfXzJtZJZP4kdo5utdn7wbbb1ZjyBCyzEuGTK5djTfNaSY2yeUqVWPruxGKIMpYDyQKarBj//8i+f3EKCT1ejz5V+D1ukbV0F9bExnyGyC1fc7qKB9cZT9HHIafPBe1iMHJPs+nhnA==,iv:UGDhNQY746zT81obqD/s129bZoriowuBRTKXn8BBu4A=,tag:KT6EOPbVQUACav8bO3R6Qg==,type:str]
    auth-secret: ENC[AES256_GCM,data:gU7mb3dFwhY1LZVZ8zhw9RGZNERcfBwGJ14xRNudb1OQ81K+mvRlR7aRsKIWrvGbW0Mxk96Lfmco8g==,iv:kCQwTV3f4y1WSMqQt9Kxe9uJPAZXBGIp/tEjq4uQno4=,tag:RkIWZQ7JlLWDX8ck8iy4mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWTdhU01nenV1M2NoZ3FW
            YU5taDgrZnM5T0FQQWZIUGRPc0pIZitGYWtVCjFibG5CUElEUUlZTHVLOE9MS29O
            T3hmUms1cEVJUWpja2FldE80MFZRR28KLS0tIEFLWXZTNGhmK1V3eGdCY2NyTlcr
            QU1naW04N3hmTXZmRmY0N3crd0I2UnMKD0Qg0MtUgw2a4XpEujGBySC1Nwg50uuA
            9OnsFU/DJwhgTVUffnvlpC0RRViN2IQEsGYv330m97rEtSutTyLzGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T02:11:02Z"
    mac: ENC[AES256_GCM,data:teJnRGWD4sgH6hK5xfJE25FCOgL7oKxKYKsm2RuXxXSF+HXHnkyyBPwo5w+WB3vMZb/+k+tFHBs0FPIp+K6SOPh3KoiPYmgGYky2qN7bRVTrYBczyX6WqW0asGgwP3422WeIep2VaCVo5gqUE6bxQUXd93/rLUpDA+Sz98potQo=,iv:N9vPjLi4nMb/gJXhrKdpEDQ6G0kJVZZnQJSX8WCqIX4=,tag:NZHkhtmPgbQ5YjMNg0PChg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
