apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:3VPCkFUxyL6GJXeGonlzpcXTMo7yAR9Pz9DDiV0MpjUVGOMqhAs5l83CeFsO1ATckfOBG99k0r1hPNM+jHsZFIotpE2JZTcWJo6OljyYab44MCQudvtipMIz6RIVWUKQHw8PRZ0HgY78aWznKBFCP5q0USAuzPRsLT/Kcdp/5SkoekJMuW+B9w7NsH9yCVvFvQ==,iv:jVLGQzUdD/0vndsvJWTtKsmRd3htY2f/TY1uSIaqODk=,tag:XCbahrnD6MYcr+se49sfaw==,type:str]
    auth-secret: ENC[AES256_GCM,data:gU7mb3dFwhY1LZVZ8zhw9RGZNERcfBwGJ14xRNudb1OQ81K+mvRlR7aRsKIWrvGbW0Mxk96Lfmco8g==,iv:kCQwTV3f4y1WSMqQt9Kxe9uJPAZXBGIp/tEjq4uQno4=,tag:RkIWZQ7JlLWDX8ck8iy4mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWTdhU01nenV1M2NoZ3FW
            YU5taDgrZnM5T0FQQWZIUGRPc0pIZitGYWtVCjFibG5CUElEUUlZTHVLOE9MS29O
            T3hmUms1cEVJUWpja2FldE80MFZRR28KLS0tIEFLWXZTNGhmK1V3eGdCY2NyTlcr
            QU1naW04N3hmTXZmRmY0N3crd0I2UnMKD0Qg0MtUgw2a4XpEujGBySC1Nwg50uuA
            9OnsFU/DJwhgTVUffnvlpC0RRViN2IQEsGYv330m97rEtSutTyLzGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T02:30:49Z"
    mac: ENC[AES256_GCM,data:211mB1n9yhCT9WSnSYDgju8iwk8ZIYeVo9HqIlhUk/DfNzruiyCLxJOsmE14//oVObr79RDlnsSHpu52Cy55wMN4r5fPZv6ixY4qzBhCkywNWxt1Za0/jibxxaISpKUCV0DJB2kqaLeCXDnR1orJbcmw4dHeLTqUDrNB+zYlD5E=,iv:k2uydOG8KtUSAQVkW+4New+Ppbkq5Wmhi2sEaIP7Dtw=,tag:NMDo6RI/arMAAom+XcT71w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
