apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  labels:
    name: vaultwarden
  annotations:
    kubernetes.io/ingress.class: nginx
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Self-hosted password manager
    gethomepage.dev/group: Apps/Services
    gethomepage.dev/icon: vaultwarden
    gethomepage.dev/name: Vaultwarden
    gethomepage.dev/weight: "2"
spec:
  rules:
  - host: vaultwarden.pacholoamit.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vaultwarden
            port: 
              number: 80
