apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-5d307713-b775-4343-ab86-f4c8252c439f
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: pvc-5d307713-b775-4343-ab86-f4c8252c439f





