# LINK TO INSPIRATION
# https://github.dev/Michaelpalacce/HomeLab
# Search for SOPS implementation
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: "0.18.x"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: vaultwarden/server
      tag: "1.30.1-alpine"
    adminToken:
      value: $argon2id$v=19$m=19456,t=2,p=1$TVFGVlVDMEpJMnZQbHVLbEl4NWJVcGYvREhyazBScXBYQU5PaTE3aE5Jdz0$vyl46eeXo+JMsTGuO5BfB8sb7BvdN2xaLt7wNX58plA
    signupsAllowed: true
    invitationsAllowed: true
    data:
      name: vaultwarden-data
      size: 5Gi
      class: longhorn
      keepPvc: true
    domain: https://vaultwarden.pacholoamit.com
    ingress:
      enabled: true
      class: "nginx"
      additionalAnnotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Self-hosted password manager
        gethomepage.dev/group: Apps/Services
        gethomepage.dev/icon: vaultwarden
        gethomepage.dev/name: Vaultwarden
        gethomepage.dev/weight: "2"
        # gethomepage.dev/pod-selector: app=vaultwarden
      hostname: vaultwarden.pacholoamit.com

    
