# LINK TO INSPIRATION
# https://github.dev/Michaelpalacce/HomeLab
# Search for SOPS implementation
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: "0.19.x"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1m
  values:
    resourceType: Deployment
    image:
      repository: vaultwarden/server
      tag: "1.30.1-alpine"
    adminToken:
      value: $argon2id$v=19$m=19456,t=2,p=1$TVFGVlVDMEpJMnZQbHVLbEl4NWJVcGYvREhyazBScXBYQU5PaTE3aE5Jdz0$vyl46eeXo+JMsTGuO5BfB8sb7BvdN2xaLt7wNX58plA
    signupsAllowed: true
    invitationsAllowed: true
    data:
      name: vaultwarden
      size: 5Gi
      class: longhorn
      keepPvc: true
    domain: https://vaultwarden.pacholoamit.com
    
