apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-sso
    namespace: default
stringData:
    client_id: ENC[AES256_GCM,data:bXvWU/oADdy+2DiAzYNZEx2mRKz4wPnFce3J5DjuuDFHjuVk,iv:HSSuBC8qbEwSN0jTa2k2BF3Hr9W/krRwzfyJVwtdyrQ=,tag:gFwbL934DA9kz8OTJDii2Q==,type:str]
    client_secret: ENC[AES256_GCM,data:TdT9S8bOhBcRgTa7j32g4g2Yj5kbSVADM8BAdVlBzUs=,iv:RbsHngFyHWoRN49d3vqQTlo3zOLqYiEH05o1piAcn60=,tag:WBLvUesFSCXuQ49fXBa0qA==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOUpqRnA2V3k1S0NpeU1O
            clN2TzZmUk5OWEJlekNLODhrTk5VY2JaSVNNClpCOGxHSml2MkVwTnRiVU5kZ1Jy
            WktsVUFvSnk0SFFzd3ZpY1ZBdU50T2MKLS0tIDNKdEV2MVQ3Nkx5Zm1FdnpmOEto
            YndhU0pFRnRERHNBU0FRTnVKTFpKYWsKfh80dEAREl4IJ7810+807oFGkOkg6Fg+
            g0vMtr0aICK+iZ7c59QUWMU9dpdkm96WyjsDJxopMJK5aNXeoBPzSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T02:03:54Z"
    mac: ENC[AES256_GCM,data:uIftEBaClSPr/4m2b3KuZudcRn9n0UNifjLaoW3YPSaDcdpAO47a4B3vODWYaXklzgdvsO+RWSdU/ZaLwIgnks3z+oCRlgV+o9SOhvYFfXgwtNH7ZnIV96J/zJrui7ZTdAte8gepnuo9n3R1/t89bkKpKy1B1empogFupC4wW2c=,iv:mg5/+EEVd7pxpD/KnoF0dNiGcnmV6AlGkcLGkFNOtxk=,tag:LaJTEMp3kviwPyF7ftMt9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
