apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw
  namespace: openclaw
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: OpenClaw agent gateway
    gethomepage.dev/group: Apps/Services
    gethomepage.dev/name: OpenClaw
    glance/name: "OpenClaw"
    glance/icon: "https://avatars.githubusercontent.com/u/252820863?v=4"
spec:
  ingressClassName: nginx
  rules:
    - host: openclaw.pacholoamit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openclaw
                port:
                  number: 18789
