apiVersion: v1
kind: Secret
metadata:
    name: openclaw-env-secret
    namespace: openclaw
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:eoDDQQyueKRvEQaGHO6hpl4Z+1HIyhx7gKSAES+j9iHWHFVFdfRr5PphbotifygITXBd1g+iHnPRpd+DEUz/rtSRUYjh7VUeGA==,iv:+IZ0cQYW16FPGnY4CSSCgF+eFucy2NvE06rflZencUg=,tag:kYSC9ixfz3YXvKECVMDY2Q==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:56sddKJ4RiqWdbLLf25kJNBUdlTK9ImO0ApEr/DXXY9SxKeFhbL8PwH0CYg7IbERsOK4czFMugZmK2cq0+Qs1A==,iv:fflfExxc0dQEcxUuEoNDNnJ0AOskVFFyWXHWarQzkEk=,tag:t7dLq7Ub8Y5t0YosaYq2Vw==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd0pqNG9wTS91dEJPdHdj
            TVMwZS9aZEZaekh4dDlUaEVmY2FMTEhNNldrCjBidDZyRHBXbGsweHdJQkxqM3g5
            NER1Rk5YYzVOVE5Ha0ZDcHZ6M0ZlQ0UKLS0tIFNLV2N1RGNWTzFiZVI3T2NlZ2cy
            ZUdkZlY4V2ZMYmt6WDlPOVVVZlJiYzAKCm/DKd5n/9J4cMN0Spap4s0f31Q+Icax
            h1CVx1gpMRykcVleUNQMFKRCWZdcZM95tkataLZDCIZeReQEZXbNhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T01:54:49Z"
    mac: ENC[AES256_GCM,data:baGujWADM/l08VlgQPoApQymrBakZGdIXMBGAgg88xCxLxFhA4JLkqWjXXHtjIKQMhkaYb0gcMnXhGydgLE//jt80pKldGaSaqhjgVHRxFMSYu3liNU2uOLffr/FOlONdCPi64QwSyR1uc+BsaptDQqqSYDBLaXSDicSj4K9IV0=,iv:chLLU30L8IzbpGowIdWfXqJlgnfV0iQWHNwDLSWaesU=,tag:TWJRy6t6XSmgjmoSqKOK/A==,type:str]
    encrypted_regex: ^(data|stringData|annotations|)$
    version: 3.12.1
