apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: open-8gears
  namespace: flux-system
spec:
  interval: 30m
  type: oci
  url: oci://8gears.container-registry.com/library/
