---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: reactiveresume
    namespace: default
spec:
    interval: 5m
    chart:
        spec:
            chart: ./helm/reactiveresume
            reconcileStrategy: Revision
            sourceRef:
                kind: GitRepository
                name: flux-system
                namespace: flux-system
    values:

