# For exposing UDP port through ingress-nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  # References wg-easy UDP service in ./apps/wg-easy/service.yaml
  51820: "default/wg-easy:51820"