apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1m
  values:
    admissionWebhooks:
      enabled: false
    controller:
      config: 
        udp-services-configmap: "ingress-nginx/udp-services"
    extraArgs:
      /nginx-ingress-controller: --udp-services-configmap=ingress-nginx/udp-services
