apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: snapshot-controller
      version: "1.9.x"  # Do not change, this is for longhorn compatibility
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: kube-system
      interval: 1m
  values:
    image:
      tag: v5.0.1 # Do not change, this is for longhorn compatibility
