apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maybe-finance
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi