# LINK TO INSPIRATION
# https://github.dev/Michaelpalacce/HomeLab
# Search for SOPS implementation
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: default
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: gatus
      version: "3.x.x"
      sourceRef:
        kind: HelmRepository
        name: minicloudlabs
        namespace: flux-system
      interval:  1h0m0s
  values:
    image:
      repository: twinproduction/gatus
      tag: v5.11.0
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Uptime monitoring
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/icon: gatus
        gethomepage.dev/name: Gatus
        gethomepage.dev/weight: "1"
        gethomepage.dev/widget.type: gatus
        gethomepage.dev/widget.url: https://uptime.pacholoamit.com
      hosts:
        - uptime.pacholoamit.com
    persistence:
      enabled: true
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: local-path
    extraVolumeMounts:
      - name: secrets
        mountPath: /mnt/secrets
        readOnly: true
        existingSecret: gatus
    secrets: true
    config:
      alerting:
        email:
          from: "uptime@pacholoamit.com"
          username: "${username}"
          password: "${password}"
          host: smtp-relay.brevo.com
          port: 587
          to: "pacholoamit.tech@gmail.com"
          client:
            insecure: false

      endpoints:
        - name: Homelab Dashboard
          group: Apps/Services
          url: https://homelab.pacholoamit.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            - "[BODY] == pat(*<title>Homepage</title>*)"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true
        
        - name: FreshRSS
          group: Apps/Services
          url: https://rss.pacholoamit.com/i/
          interval: 60s
          conditions:
            - "[STATUS] == 200"            
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Developer Portfolio
          group: Apps/Services
          url: https://www.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            - "[BODY] == pat(*<title>Pacholo Amit | Developer Portfolio 💻</title>*)"
            - "[RESPONSE_TIME] < 300"

          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Linkwarden
          group: Apps/Services
          url: https://linkwarden.pacholoamit.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            - "[BODY] == pat(*<title>Linkwarden</title>*)"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: n8n
          group: Apps/Services
          url: https://n8n.pacholoamit.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            - "[BODY] == pat(*<title>n8n.io - Workflow Automation</title>*)"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Vaultwarden
          group: Apps/Services
          url: https://vaultwarden.pacholoamit.com
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            - "[BODY] == pat(*<title page-title>Vaultwarden Web</title>*)"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

          ## Infrastucture Section
        - name: Proxmox
          group: Infrastructure
          url: https://pve.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            # - "[BODY] == pat(*<title page-title>Proxmox Virtual Environment</title>*)"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Speedtest Tracker
          group: Infrastructure
          url: https://speedtest.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            # - "[BODY] == pat(*<title page-title>Speedtest Tracker</title>*)"            
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Truenas
          group: Infrastructure
          url: https://nas.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            # - "[BODY] == pat(*<title page-title>Speedtest Tracker</title>*)"            
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Proxmox Backup Server
          group: Infrastructure
          url: https://pbs.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            # - "[BODY] == pat(*<title page-title>Speedtest Tracker</title>*)"            
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Longhorn
          group: Infrastructure
          url: https://longhorn.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 401"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Weaveworks
          group: Infrastructure
          url: https://weave.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
            # - "[BODY] == pat(*<title page-title>Weave GitOps</title>*)"                 
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true
              
          ## MEDIA SECTION
        - name: Jellyseerr
          group: Media
          url: https://jellyseerr.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Jellyfin
          group: Media
          url: https://media.pacholoamit.com/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Tdarr
          group: Media
          url: http://192.168.0.53:8265/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: QFlood
          group: Media
          url: http://192.168.0.53:3005/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Prowlarr
          group: Media
          url: http://192.168.0.53:9696/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Radarr
          group: Media
          url: http://192.168.0.53:7878/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true

        - name: Sonarr
          group: Media
          url: http://192.168.0.53:8989/
          interval: 60s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: email
              description: "Healthcheck failed"
              send-on-resolved: true