apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hatchet
  namespace: zentech
  annotations:
    kubernetes.io/ingress.class: nginx
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Lightweight workflow orchestration engine
    gethomepage.dev/group: Apps/Services
    gethomepage.dev/icon: hatchet
    gethomepage.dev/name: Hatchet
    gethomepage.dev/weight: "3"
spec:
  rules:
    - host: hatchet.pacholoamit.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hatchet-stack-frontend
                port:
                  number: 8080
