apiVersion: v1
kind: Secret
metadata:
    name: hatchet-shared-config
    namespace: zentech
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:4VnK4m35DtmaqtARcLDDpx2ZfrV3QH6IhwOucjpwWgYwVMrsfst5jkQ96bWpq4hfioeRVg0HYlMg2bvaorw7jctQwksT/iayDTdhqseCIgB08LsocQIJCbTicwYbbHddft4qo8E2PSzLzLA=,iv:Y9Pyn0BAgrfZ7+Y8TSPg3edwAxENJLxtzSKvZMLcnJ0=,tag:6DtiQ3AwxTgFBdtwnt9k3Q==,type:str]
    SERVER_MSGQUEUE_RABBITMQ_URL: ENC[AES256_GCM,data:nPOnELYlbQSDsuSgfkNT8B3lrhttdtJ7QaFheoaon2etfJHgp+U2RpmfPwVmA2pZbxGk1CMZDhroSXemYfaMy9o/H2/TVib3AMOkpw==,iv:OB+l6RwtJ4ujVGCymfXTb9+dZh9pjcqtMh2ML3TB2rY=,tag:3QhlynMzhw4J1ryidpQaQQ==,type:str]
    SERVER_URL: ENC[AES256_GCM,data:YjAVUPpIG0MZkj0IcOY9oXqIVNK25bvjmz8o8NyOZQ==,iv:2aFXnIgPn/2t0tHse60aPMSuaS4g4j6Qi03hoXSAJB8=,tag:kibDmAC1OREsRFIMhrqfEA==,type:str]
    SERVER_AUTH_COOKIE_DOMAIN: ENC[AES256_GCM,data:VWnoyl+Eo/Gr7mIopp61RithJFURPIQ=,iv:AICS+Brb5o3uKCAPG5V43GVIroRZHaNWW9ftjpeW9qw=,tag:Vfg7PhQS0yIDxIHKlrNpyA==,type:str]
    SERVER_AUTH_COOKIE_INSECURE: ENC[AES256_GCM,data:eA==,iv:s8UkKpk+7Il5bDUl/E7MMLbD+9v2bmrt8MFQro9oGuY=,tag:FW2sTHpSxOiK+nuwWt0efA==,type:str]
    SERVER_AUTH_SET_EMAIL_VERIFIED: ENC[AES256_GCM,data:rA==,iv:z0B3jZkS4ghXSZ7LULhXeoUQGF2YPCzSXM5UPMBMqrQ=,tag:t9luSzjx2qndzM8mcdACbg==,type:str]
    SERVER_AUTH_BASIC_AUTH_ENABLED: ENC[AES256_GCM,data:hg==,iv:dYRgScofPlTbvOHvnJM25OyanG44mLuCi2833O6vwkg=,tag:+9cP6vP73q/UzAJgptQeVQ==,type:str]
    SERVER_GRPC_BROADCAST_ADDRESS: ENC[AES256_GCM,data:7x9+ITJB04ChQcBfeX2cQlFrFr7pKQGlf5bXg/13MPstPQ==,iv:JvHqk5PXtFQwZwYcZIJNpFLAkl/eyQ9yhjM9XGPMNJg=,tag:DdlQbs/epoxOYDqQcnihcQ==,type:str]
    SERVER_GRPC_BIND_ADDRESS: ENC[AES256_GCM,data:Qm67H6CEg2lJDDzw,iv:S4vyIklON9T5ehXm3wL9XGf9Wpzk07pOltKidQFM63k=,tag:n7S9B5fL5yv9BPB21NnIAw==,type:str]
    SERVER_GRPC_INSECURE: ENC[AES256_GCM,data:ug==,iv:o2iPMvshh7oELz67ZTgTTa+KAQno7GrCgps8Z4/FZdc=,tag:YXKe+jJceGkwEo8ZQbpzfQ==,type:str]
    SERVER_ENCRYPTION_MASTER_KEYSET: ENC[AES256_GCM,data:/EX2nNkcQ0zsv6Eo8cjIwEFg0yg/AjTo1JKM91gtjUoRRwXZQqKPHpkkCz2/eZtuSh2dsQhGlxS/e2CxUYvOYQ+QzBfsf8Ao5TvDBxOxMf8kRQmNTBXGO+xdu2wU6KG1/Wr2MCn+xPCJcsWrj0SzZAsM5P2lGSI1ZySaxxC2yRNSWLyka7+EoDytx10iugIz1MtEdIrnfK/saNNBFVXRBUrxLR9UlyEQW7O19MuvfZUTZhTK+YAvpkLpOcvHhZWnqb+Sc82WJncexW9RD+GEIaSLizm3FxFMC2rChcdop0nv/OPVTW/ILRn6rg6nZ3pEWqcMtDEgGetqzRBAslX60zWePN/y+u+BFH2xvRRElXg4/q8BIfbvojKDM/ogA14ach+/YYEjlWzqdy4b8nJVOcJqSawPjBrZhh/aJCkszARXg/tKD4hqtd6BMcIOSINv74LFrgpsGb77+H02o18Y,iv:X7aWqwD3kRAMyTKEV2VETmh1St3izn8yVdcvWK+5R5s=,tag:Ry+q7iKrrrIRYhnN+BkBYw==,type:str]
    SERVER_ENCRYPTION_JWT_PRIVATE_KEYSET: ENC[AES256_GCM,data:VGdT5Op4es/Cs2C7nZnGhcqASd/NdgLPSNcR9rxog2g7OL4lj2yTAOWn5d4LsCi6BbWf2cZHQLOeMyiJvSYMPfm+nqFHu5v0mCOcOz80DUafA68obuD+cIbiK6S0Y2CK6qsWstK77KoEn7zSFup7KJ+Eeg9BouNINsdxwNVXOuvmmBivponwP3awYeJECxtUqdR/yE4sGapKZfsWx+z0TQhxG1zybg0o+Sv3LiHpwpL5ZG/FCgNYVPXcHSwIyF2y3B7EiSpxmeL3IEGFUliowRknRr++duKAa5C206BSu+YIB3zeEWwFffSVNA1T6uNAgUk3YVCYX0FrMYjfpcX8qlj/rhczlyiXve+wmOIIsGHufMbgYBLJSjr0xh3eKbUgO9pCS4AW0FDPNyjxNwc81cf/ujB5DaAwiCxAia890Vb5ft67eeD/8ARfxsYrD7DA8MJ6oAseWI5LeTAlkM0P/j7la1ZJ+Qurl2yfwUZI0NT+FmdrBz4p+6QhNpEvrT8HWMrnVJguDDvqsl5wug9o3YMtTROt6ORO1s6cjrMrfTEuJZoriknrFefs9yjN7RwsuQY/I9vcfkbAie7C3rzD0umKryrhrzlhwni/6pDOsGQlxQlVgnKHW36LN3bX7FBhZd4iv9ZaDtwQXUwfB2HbLbD1GTgvPjZirYlKny7yaflq3Vz0f25xQxCrbljQRIkDX/LoaBm8NyxP49HkUdrAX+2W4TdfZcVU7I35HRS8mh9XqZGQzWKWLcb19ExafKVNj9xDKaqWeEKiZgalGfIh1gx1KwMXQksiCqT7xcwz1IXOrHVpZ2JofgslYWCwY219Yz7FXwfIQgKJwFNyHZnUJUFXUt6ROKP47zvgQga+xwE49uNuLGYRyQyo213G+cZSAmVAFQcTgQ==,iv:alI0BpaYmqULtetpbD/r62Gp6l/qfeYAhBstVV0OUbA=,tag:qEJv+f2OGEyR1K9gkUgFJw==,type:str]
    SERVER_ENCRYPTION_JWT_PUBLIC_KEYSET: ENC[AES256_GCM,data:9xBvigkHn0hK+5z+oPajXZefX9G3Wp4W53GWPtJAmEPLQDShsVV592xjNZBpRDn1FkEe7ljtuAWZJZR1Q+5ha/M/Gj79WJZxHjzYmEqHxHwCLjov3fjJh1yi3Ym9BINaoIVq/7TnKpfjIsjr75KdSJ4LUJsLFg8tz24j/9cxXFRfmnBF3ISj4tAlcp1MpqyI+MpKcC3F18WQ2hpGfyHmIUtOv14BLH5V44J+9d7gehC3NAN/J+P62BeCKRgbkrzKJtbD2mOdHaiMql114hoF9paAU+LKmxfFMDlHAtUqVco34/8PDQqm5eksl68k8j07qApmCNdCqM6BxBEVhvDE7cvG6AKGWN9rbJGcKG1wS2SVgzaFnl9wEWitHzQHYopcpnSLSBu0qo6oKQP4SughNWSLOrJV+zNBOCDSExp7zdLyWDHBOpIec9sCPngUYbw4XCkxymP8iCFPqFYMg5qEZ7QxgefHvtKsKDTR0mWBrmCX5iy6kzGXRpwvCgWsQdsKIe576x3tvszw5FbWfoHyikSJDfvpJNBrLhwvEXNoDT1482VifjajJJMwYkaByPZE0nEQEr/5SaDPQgSBWSMA9DtUnA3vDmvTRzUHvG3MmoogmQQ9hJiASORDSf81CSS1A2Icucl6lq8HvGgKtzN5Xb6CMk4bXihG3A1AKO8UTq000d1Mg/fQPKWxIIk31IYoFNgcgfCAranGWJX47/t28LChITID/mT+ql/oLaXE6MFUQpOtPohfkMRQnDhUQWNetvVlio/72ilz0OjxG1lgmQz7nbdJTJ1yII0es3EVtENbn7ToD8k=,iv:htuKrsFSF6yDOBznEbRVnI2tlnL2ODsl+fK6FcIDkKg=,tag:LHAocvLSW3giJIluoejNCQ==,type:str]
    SERVER_AUTH_COOKIE_SECRETS: ENC[AES256_GCM,data:f7RhLgA/R/WE0AFX9mcT/HowSNZInMhU6HEbWaRYsOw5zM4XkPPFjeIDAow=,iv:ag1/ByNEn1cayv7qTJ0HkJ1Jsuc8eb1FJZBeS6qMmVk=,tag:pwCEuz0wh1tMnXy66fgraA==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:oEncEKI4cPgJP+Ygg4OjjoUMTCfJ,iv:gFfSdqYcpfvz2coGPuwbWdR81R7/lWY+uep6G235FBg=,tag:rhOahs+uScDXnKjfXcDPOA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:pespCsxhokE9gF7tjNkY7YNa/0BTOGEy,iv:7B+Af/fDKEKJTIwSa2qW1j9eCT5xgFYHWBUPul/gnZ0=,tag:MXGu/DbE+vQS4paDcd7vpA==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3VKSCtRVCtGR3BTbC9L
            UVpwYmkwbjRGcU40Yk9FWVBlays3R3AwNURvCkVMZnF6QnJFSkRna0xjWG9tQTRy
            bjdDazZEbHUxWmE4UnBzZStiVXRQcW8KLS0tIDlUZzNJVCs1MDBCVStIcGdSUVVF
            bDE4WC9YeGJJZmZFbDNXd3hWZWRsaUEK23FLMGRd1V3vU+C8/X+1GJ9n6bd7BFES
            xsWeBaOaQOtT5iUkD0hL8EWdeCDzqwchJ3LTvcU0ynjGKZKuD93tcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T00:40:19Z"
    mac: ENC[AES256_GCM,data:9Q5VnzxWNt4uALyZ7BgXh72Ho2SA7M5BoePGBUa0fnd0ux+Np9IbkyBT9D0OYC90OM/1SpqC/y5HowwJf8XY7w+satANbFA+2Pm61UJy0cqCSsGMqzR8QNhL9KB9zaBY6DcEe6+JnOFmDzK4BPo/qG9HNsKQPaG9QH1rLLmOTo8=,iv:5r63Rk3QcIaVCZ/t51PIlGUVTGelnMPBiXSKXVkh/2w=,tag:jn2lvWUvpDXVPqgW5eY9yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: hatchet-postgresql
    namespace: zentech
stringData:
    postgres-password: ENC[AES256_GCM,data:EqiB1zZG8PLOlxlvlwYQO4rLE4w19bMV9+N0Zhu7L9c=,iv:+/E9uE03wT1a7CAIufAbcC8z5N4Or6SmUNuo6cJw/nk=,tag:4ov9fJtF+OBISPlkOFPkMQ==,type:str]
    password: ENC[AES256_GCM,data:3Q+T8a7jKHy34YsE8mbzeNImvN0tGz+ZTNdmebsszBk=,iv:P5BATaZvMO9R84l00SgMqVYsbGUia6QP/xnirUK9Tvs=,tag:YVEpBHegFm9brI4Nj7duPw==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3VKSCtRVCtGR3BTbC9L
            UVpwYmkwbjRGcU40Yk9FWVBlays3R3AwNURvCkVMZnF6QnJFSkRna0xjWG9tQTRy
            bjdDazZEbHUxWmE4UnBzZStiVXRQcW8KLS0tIDlUZzNJVCs1MDBCVStIcGdSUVVF
            bDE4WC9YeGJJZmZFbDNXd3hWZWRsaUEK23FLMGRd1V3vU+C8/X+1GJ9n6bd7BFES
            xsWeBaOaQOtT5iUkD0hL8EWdeCDzqwchJ3LTvcU0ynjGKZKuD93tcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T00:40:19Z"
    mac: ENC[AES256_GCM,data:9Q5VnzxWNt4uALyZ7BgXh72Ho2SA7M5BoePGBUa0fnd0ux+Np9IbkyBT9D0OYC90OM/1SpqC/y5HowwJf8XY7w+satANbFA+2Pm61UJy0cqCSsGMqzR8QNhL9KB9zaBY6DcEe6+JnOFmDzK4BPo/qG9HNsKQPaG9QH1rLLmOTo8=,iv:5r63Rk3QcIaVCZ/t51PIlGUVTGelnMPBiXSKXVkh/2w=,tag:jn2lvWUvpDXVPqgW5eY9yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: hatchet-rabbitmq
    namespace: zentech
stringData:
    rabbitmq-password: ENC[AES256_GCM,data:WPNb9AnOakxtm9ECrtWiizSjFhlijiICwgHjTiNda4w=,iv:WO3JwgGXynQ8jctufMyIKvOPW8Q57Bs5f9G7HqxU+a8=,tag:NKPMKUa1Dk83CFCYZ+vU7Q==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3VKSCtRVCtGR3BTbC9L
            UVpwYmkwbjRGcU40Yk9FWVBlays3R3AwNURvCkVMZnF6QnJFSkRna0xjWG9tQTRy
            bjdDazZEbHUxWmE4UnBzZStiVXRQcW8KLS0tIDlUZzNJVCs1MDBCVStIcGdSUVVF
            bDE4WC9YeGJJZmZFbDNXd3hWZWRsaUEK23FLMGRd1V3vU+C8/X+1GJ9n6bd7BFES
            xsWeBaOaQOtT5iUkD0hL8EWdeCDzqwchJ3LTvcU0ynjGKZKuD93tcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T00:40:19Z"
    mac: ENC[AES256_GCM,data:9Q5VnzxWNt4uALyZ7BgXh72Ho2SA7M5BoePGBUa0fnd0ux+Np9IbkyBT9D0OYC90OM/1SpqC/y5HowwJf8XY7w+satANbFA+2Pm61UJy0cqCSsGMqzR8QNhL9KB9zaBY6DcEe6+JnOFmDzK4BPo/qG9HNsKQPaG9QH1rLLmOTo8=,iv:5r63Rk3QcIaVCZ/t51PIlGUVTGelnMPBiXSKXVkh/2w=,tag:jn2lvWUvpDXVPqgW5eY9yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
