apiVersion: v1
kind: Secret
metadata:
    name: hatchet-shared-config
    namespace: zentech
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:CPJYpbuBPqwjzL2zkijSEY03aGoMHT8tvDRf0Urd2fluKdJS9OU50hVyg8n1A8Cz7aORPJkV9sq0tc7HB5qestVg56+/staLK+YTj2WuyMrKntorF44WwZceEGMv1LmX3mjvjv+CcH6QQDg=,iv:5TMTNwRhc+oVwy6aUFbVgbFbOKJp7YYOsvQ+nJaK5/I=,tag:1foyFbcLjaoF4kzhUXNAjA==,type:str]
    SERVER_MSGQUEUE_RABBITMQ_URL: ENC[AES256_GCM,data:xl5QIf4QqAYXiUqQyMF/cqP1kHsFr54mIgmSBpTBAmnmdkHu0epI176q8puQ3TCmPddmkHh+XQmqKcaBGgVmnFDkXcLdQT0D7INpRg==,iv:QVHgdMzKXFsqGNXbn70vXCoehWQk7+C8imYS+uBbo3g=,tag:57Q35HKVHdYKAvfKnNmnFg==,type:str]
    SERVER_URL: ENC[AES256_GCM,data:61VTtsW4X01btJNqG1JnHLgN9CQWC7IHlFZRtQ96IQ==,iv:AnpxM2ireO3gn7RId7Wjs99wZdxGhAc5Avxq/mzK6ls=,tag:mMzbRLNjgKNRBy5fAq085A==,type:str]
    SERVER_AUTH_COOKIE_DOMAIN: ENC[AES256_GCM,data:aC2iUNg8a4GCx5c0TLXx1p4bq0Rwz24=,iv:IjjJUBEOTIu9U3XdOvASTcCupql09B9bvdAbpoOFg78=,tag:xw6x5X08OB9W9XuLThJLtQ==,type:str]
    SERVER_AUTH_COOKIE_INSECURE: ENC[AES256_GCM,data:5w==,iv:Roz9UIhf0aw/Y34ScbMX5hkKJHmZrariQVKdszqyGoY=,tag:oDcECWDH0a0W795fa7sd5g==,type:str]
    SERVER_AUTH_SET_EMAIL_VERIFIED: ENC[AES256_GCM,data:hg==,iv:mSe9zzgT8aDJ9DQBC8GCuZkrx18HcGfEexzNVXcpQzo=,tag:K9bcq8Yh70iXujYMQZCJLw==,type:str]
    SERVER_AUTH_BASIC_AUTH_ENABLED: ENC[AES256_GCM,data:6w==,iv:EFO9En5XId5SrFg+asc7InvtIXXzq0+NfMqCkgx7QdY=,tag:ZnCjEnf/gwJZgpr0MFk5BA==,type:str]
    SERVER_GRPC_BROADCAST_ADDRESS: ENC[AES256_GCM,data:SE92LwInXaZpfMJd6DDlbjf194mmfJaqBAUHhRWZTW5r0A==,iv:3njRt3X8tEKmlRKIYTczi8BeXToZVGRE+kpNi4cdxzc=,tag:TcUdZYDkWAjOJWM97QdGJA==,type:str]
    SERVER_GRPC_BIND_ADDRESS: ENC[AES256_GCM,data:LVOv+vlJ5qTR/D+F,iv:n1nmkaSbpwt54AVRyOFlPshIdHcNnZcovt4PWpZZLsc=,tag:VBUVow2Ir3QttPL7prf3rQ==,type:str]
    SERVER_GRPC_INSECURE: ENC[AES256_GCM,data:zQ==,iv:QmEVEFGLGK77uvMC48olw+88/gzjxlSbxsyWHV1sfcE=,tag:2ktSFEFl9XuM7olZHJg6sQ==,type:str]
    SERVER_ENCRYPTION_MASTER_KEYSET: ENC[AES256_GCM,data:In87y7/aCdcDYyuu0JwqpH5MD2/ATjM6xwl+14HjlwsbkDY6K83nl+hlnAh6UN40XVr7ILlNw1Y8WPW11tK5jenMWjz08VO+Bb2ZJRw46+G+ndhV9EHR2XQ7WiEYiSqYvljezPTpPFElMXssItlXaWV8r9mf+x8fmFM2PseRbekIXXxtC9+eeEeK1D97MvdbBJ1wFEHb+De+jwVHdxFiZ+yEEgQPHM5aYDE8LcYJ+6PICuZOy9Lz1KLiHeHnvg26JA2BXGe9B4D3tafFnr0Kmh5egHKWVD/RVgmdl/W7WQhmDVSkCUdR7MLETFZh30GZLBbFJHqAU8Quy9B8oWXicOf53yervWFu0sO0B5dxuOd2CbKiCvPqDlw+FWC45+Lb1Mpi7PzoGVvGuokWLbKkc6tdhqSLn145G6p16uiNjHhkIDg3xODjF8LUfd/EEvaPF6OJ5imvO/OSVKHzp2nk,iv:9U8OfxcWZ6fX7gustUklPUoEL921SVbZ8lA2Nd6FI2E=,tag:jrZzAd+uKwwYmvFKBVRwlQ==,type:str]
    SERVER_ENCRYPTION_JWT_PRIVATE_KEYSET: ENC[AES256_GCM,data:XX05aVh0Qr+BhZk2EcI/ERPdLT9ZfNg3Zl8hpuy2LtDwHwe5TL4MxJWdFylDSFEE77vdeZdQ9aH88n48I57ymODfkd6KIn2nZiGruetwBWUWg7me1JmkUEp55/SjPy1vlWxWZkaDu01bKCSt2OOtYeUpRuZqYv3+EWA82iiJ9dbKeZKAB1n8lfIIl+LYy9hTJ11QddE2I+Fs4+IRcVbkJGRLcyQXdKbI4R5BOn4qZnSzQD6Vi0NJm9TKlS/MfbfCTsocRhLcUQc30B6DmFy3/8NI9lfmEQjSWnoZgOMNwr1PYnUXSzvB8zNcXkBDYrKb6YM77F06hTC9/fNENQEw0t34Q2NsjCM8WXCHh41UlG6UyTGSVNW0Shh06TfdL+DJOXL5fFq7nbXI2DX95gcVbUFDuyKVoUmtMGPCSJZIqM53hnwQEQbByBnUPF+d34o6m81s2MeBCGzrq6WxbaALMQfUChgnn9Bv+Epluvl09V2q9YNHlQhpzW2fuNH01RfYg2rXoCEl90K99ccnWfdodYKHSVs+d5MfAhdBtmV1IycVU87sU1iPcR0lBLOkj+z8DNuV4uszvEebp7Be3BzwBZoCHPwtVuY3jNrJ2q3vICpTTy+jgq6ex0D3H92fXyLLVSh2r0CQe20qXZFYi27IHWU5y8MdBdrxpB/cImTKNBAKJIattdXJrRNKREkaJhabVlqviDU27EMqwZjPmXh+U6I4F1g9sGt7K7NkqohRRd0mkJM0iptppWyGxRBBmkRHAvWtgEtmYTFnk4Aq5DryCeJIxgDDI4lFQOBe9pMQTXIjSE4j9ovBZxkPWB8PuQW4B9EsFAWuAXb9tjkMNN4FiUMiTtX1WtiruqdTJ+MTqhyy3G++th5QSJY4iMWw6LtyLW2b5c1jbg==,iv:yp3FynEuUy/WUFZI2btCjucRtXKmoieYpdGp10eWodo=,tag:Ch4R80sc7gXOOjyIwEuuTg==,type:str]
    SERVER_ENCRYPTION_JWT_PUBLIC_KEYSET: ENC[AES256_GCM,data:JB5SsKKslIA8XiXhAOVWTM6r2f/jHwlxqdiGizdFVnRlt99RbZZ5aSXpi9ziVKczgTe295erEz6osOXie73TZ0rya/wN81pGEi30bpf//x8vQwY1/nzi0i2srpxBZLiAvDQ2n+zFJeeZjV3CeW8/QcSiWOnsbFttSqzG6H3RR7CUIWmyW6NZpJ5CIJjk1ou9H+2CfMOHAszauuZ2J8LTpGlcKQgUO3yrfOckdnD2hVxXYDhebiVEc2ABPJSsANM8Jk/Jiv70yySouQDJl+RFveGtQ0jIQYUchjdCGA+U0jYsZUq6u8h6DzNRYqUWO0W00yQ2a7UgU+nwjQKkrHma+fv6FSU0ASnVOFcX/xyBp+Z0DmAa2ArLwNuI+pP4YyJ+U/4bILK769+KjiavPLa22VnmWs0WSZl0AooP7bCf6tDb+IYb0FI2XPzu0OGdCJPqJLdLH0BNdQlwP1ayPXWaI47cBtzIlzRjpv4Xe3uD0XamS9EkcnOP8uhfpTtLqs1RvFmhiFG+/IF0VcXKo6nh9OnJBfOhl9qecKMQLhqmx+d+bj7J4+FlI8FAVjkAyo4vjPvZjNoZ0SKNNwCrc6umjN60ZEFPeuIMosUGuvZyj7PUTzmzUbL8ZmL37o8iThjf9D04pUPWi53FpAqEIHPKbMpDmkl4h5ncbRStoAxoN8/OvoF5Scpaf5nzdTQ6OS5vpAXmgfUdoBgbyszHzj93OTW+uPMtuxiZLkqLDPNn6zTVo832fg+23QRnJWyolC9sBOT0ASVvAHLLTGIkJK2Ay6TfN8cFPCx9dvIVSqZhG7v1a0qaXR0=,iv:eV4JLJwVq6WAOjz7mu8F67IuUd5qb6bQVQMXVFbH6hc=,tag:ecoIKoK5sF8KaoeA+o0jsA==,type:str]
    SERVER_AUTH_COOKIE_SECRETS: ENC[AES256_GCM,data:17lOIOz3DnmMTKSgxN/nVu/AIlow6O/0ydPixpIlqb4b8cda037EKSVoPQA=,iv:yg67sH9tHx1OGxO/Dvik/6uWhXhBAnTnazzy589zH6Y=,tag:J/GKbPRh7EjKMM/nj6JTmQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:AtgjH5rJ0FZqaaPTaC8vYDYFLVs7,iv:TXYlx0X/5Oxs37D/4tJO5hIyAwHWXjXOZcf557RHVVs=,tag:SvsWtfa/5L/GT58JHAohiQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:NDR62utNGiZ22G02fKvnvwZgDUP220mk,iv:1iEvbSVOOv56VtIp0l083T3o4IIIcmGOp6HMC/BunrQ=,tag:y3IVjh1cfReyo5ynuQjSnw==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVVU5bkpCSlZ1bVQrWXBP
            MnNCbXY2N1JBUXJCcThMUnBOSXpQT1p4K2dVCnZUUEJEbjlsR2loQ2RrRGdNLzU3
            UC9WMTZGLzRWNVFWUExScDVHdUg0WmMKLS0tIFE3RVpkTWN3UXc0NGpqaHNubkZw
            eXRuOFBkUnU5RTF2czJSYzdrdEJRYXcKrhSHnUM5qVSjeP3l8ggmxVB7NkX9uorl
            dnI5/R862PhdtvKiO9s64pgtwdWwQvib+fT5U1QDplbOJVfNywLOdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T00:24:03Z"
    mac: ENC[AES256_GCM,data:a+oOTgA2BJulRnLPc+6fRnk4iHHW0vOL45FxwKYlEL9g1VtVs2CQG2w5U2pwU3CA6by6wetIW8BjU3hMGrwjwMnjtRNuBeqQ0wFPs1fUD6c2I4E4Jo0x54OJU7mnTUY2T1wXfVC8KtV82rWRInnnO/bnAWWUV5yu1HVjFQjp+lY=,iv:vRSiTPTbSOb2TdizgMfr9eZ8ikrP4OXdZv/F5Qno79w=,tag:m9A52dKZuXdR4dcWpc/Xzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: hatchet-postgresql
    namespace: zentech
stringData:
    postgres-password: ENC[AES256_GCM,data:4gVKt70BtZP5ZGxWOBnvTwFfwpEPk8Swu1naOVjSnX4=,iv:sKpSLReO9B9WQtdbFTR5J3AFeXsmpjV7Z9mJ8bwujlc=,tag:I0JBuqEv2uyooegXIHxaGQ==,type:str]
    password: ENC[AES256_GCM,data:bIC8Jm1e/TXBTwRP4It+ID0HAWE3LJaW4P464KKJcV8=,iv:snb1mC46JSbWPJ5ktAnhO5qd3Xvhs1sLrfhllgRss98=,tag:paWGh5Yix1Fe5T42eGgpcA==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVVU5bkpCSlZ1bVQrWXBP
            MnNCbXY2N1JBUXJCcThMUnBOSXpQT1p4K2dVCnZUUEJEbjlsR2loQ2RrRGdNLzU3
            UC9WMTZGLzRWNVFWUExScDVHdUg0WmMKLS0tIFE3RVpkTWN3UXc0NGpqaHNubkZw
            eXRuOFBkUnU5RTF2czJSYzdrdEJRYXcKrhSHnUM5qVSjeP3l8ggmxVB7NkX9uorl
            dnI5/R862PhdtvKiO9s64pgtwdWwQvib+fT5U1QDplbOJVfNywLOdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T00:24:03Z"
    mac: ENC[AES256_GCM,data:a+oOTgA2BJulRnLPc+6fRnk4iHHW0vOL45FxwKYlEL9g1VtVs2CQG2w5U2pwU3CA6by6wetIW8BjU3hMGrwjwMnjtRNuBeqQ0wFPs1fUD6c2I4E4Jo0x54OJU7mnTUY2T1wXfVC8KtV82rWRInnnO/bnAWWUV5yu1HVjFQjp+lY=,iv:vRSiTPTbSOb2TdizgMfr9eZ8ikrP4OXdZv/F5Qno79w=,tag:m9A52dKZuXdR4dcWpc/Xzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: hatchet-rabbitmq
    namespace: zentech
stringData:
    rabbitmq-password: ENC[AES256_GCM,data:ZCrAq3h8Bi5aJY0LW+i1a4/R9Bmcw7h55jvY/xw+Klw=,iv:6ve1mhi1Kdp56Ht0NhPLSN31GyeAs1tufInDAt8PAYI=,tag:J907h8/nMSDJIsDafWas4A==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVVU5bkpCSlZ1bVQrWXBP
            MnNCbXY2N1JBUXJCcThMUnBOSXpQT1p4K2dVCnZUUEJEbjlsR2loQ2RrRGdNLzU3
            UC9WMTZGLzRWNVFWUExScDVHdUg0WmMKLS0tIFE3RVpkTWN3UXc0NGpqaHNubkZw
            eXRuOFBkUnU5RTF2czJSYzdrdEJRYXcKrhSHnUM5qVSjeP3l8ggmxVB7NkX9uorl
            dnI5/R862PhdtvKiO9s64pgtwdWwQvib+fT5U1QDplbOJVfNywLOdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T00:24:03Z"
    mac: ENC[AES256_GCM,data:a+oOTgA2BJulRnLPc+6fRnk4iHHW0vOL45FxwKYlEL9g1VtVs2CQG2w5U2pwU3CA6by6wetIW8BjU3hMGrwjwMnjtRNuBeqQ0wFPs1fUD6c2I4E4Jo0x54OJU7mnTUY2T1wXfVC8KtV82rWRInnnO/bnAWWUV5yu1HVjFQjp+lY=,iv:vRSiTPTbSOb2TdizgMfr9eZ8ikrP4OXdZv/F5Qno79w=,tag:m9A52dKZuXdR4dcWpc/Xzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
