apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler
      version: "0.27.x"
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: kube-system
      interval: 1m
