apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkstack
  template:
    metadata:
      labels:
        app: linkstack
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: linkstack
      containers:
      - name: linkstack
        imagePullPolicy: IfNotPresent
        image: linkstackorg/linkstack:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: linkstack
          mountPath: /htdocs
        env:
        - name: TZ
          value: "Asia/Manila"
        - name: SERVER_ADMIN 
          value: pacholoamit.tech@gmail.com
        - name: HTTP_SERVER_NAME
          value: links.pacholoamit.com
        - name: HTTPS_SERVER_NAME
          value: links.pacholoamit.com
        - name: LOG_LEVEL
          value: "debug"

      volumes:
        - name: linkstack
          persistentVolumeClaim:
            claimName: linkstack

