apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno-volumeattachments-rbac.yaml
  - longhorn-rwo-failover.yaml
  - longhorn-rwo-image-pull-always.yaml
  - cleanup-stale-volumeattachments.yaml
  - inject-priority-class-critical.yaml
  - inject-priority-class-rwo.yaml
