apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCmrG5Lrxz4Xpggu8P9d3WSwTkmbiZ3Xj5NtfnLr7K2eUA/KvH8J4JhppoJwt7tlA5GM8jtk5C0NOyHZv2fX/T6J8CNgVfC5qQsiUbXAltUr0hEUAHPmFaeoy/XQ2Co6/4a9giVtQRx/OQJPBj9csGCx78SPp6lOLSAl2mrPfKK6ceGfB2BzQ1lek55vE/d9qlwzcTt629KRAjUlS9HjbSJyRoV/uC0aBLw6Nn31PvCj3RXDcIvYdCS85Lu5OlsUtn7Escc9gu+yqIkBATBeoU4pKSoKKxR/d3XU3P+M/Xmv9svdVyh6+fAjsN6J2CvBp5e69M71ZgrzWsb5G1r2/JqfbnETM2mbQ0KNpsWK/X6ojZx3uRjk3F8V3dcvBa/UMnj62W0+6J9WFxjC+zoM4sFGr38HehqJx8R+TKJMzkagtWqFH0d90aKA5FBtmPjHxjwArdooVRxjXIUgmnih9n2dvlrjstYK0HZkpgg6NA2BNDu6sknzWRlcNHB2Z8NZ2dbggVstKD/sW2HaNF3ce55h+MTgpenlnmYAnHlnGculRXg+deMPajxC0j9bUIhHpJPcaxTfyoyef+FGwdf3MSP5y082VLkguebK9kpuGp6hCBwC3BuYZDSNTqfL+0zxHtQOcdLD6qWBnOLsPJBRkvRFj9zyxs/aD2acFpb5bpSEYi3pV2lx/pZmR4PalHfxIgopOfAU9mFFUmeCukzWbMGELeoontgRsPB2zXyrincKaTJkL6pM0qrEcA1maCVNihjcDUg0PfVj5NVkXf1UCZBeuFluQ5ThdxDCpsphywPVmrhwYmDbM1wF2IaE7wSBfECGthOenSanTt3EJZuxpsdhbEu4/paVC1PPBlCNWJxDB+hbDl4gw7OY7j21PUdMFZ0acBXMceuPTy00WdpYOOn9A==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare

