apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
    namespace: beszel
type: Opaque
stringData:
    HUB_URL: ENC[AES256_GCM,data:dwhGBJMqETDZfcJBfFvONPlqJYqnKETuvQ==,iv:tAumvo7gzI6UDMNKYlBVoDmysCk+UJ8B623l2bW0JjU=,tag:uUiY1d4BPRRfrz80f+OkhA==,type:str]
    TOKEN: ENC[AES256_GCM,data:NyQVigdExZBsezLojQW21uKYivjKFwnNX3rjha23yKabCgU1,iv:Mgr0BT8dTPBU7ObAcew7eDBWCtbNEjD+Z89bIWK/ajE=,tag:Wtc6qAZV5/pKquJ0LLIY2A==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1VzWGl1cXJlenlvdkNB
            RTR3YmRya1FoMmFDa1UzL0hzYy85NitqbnowCkJUQmlVelhzRnhURHVTVGNxOXFa
            TGNvRDF5UGFJOE04NXcrZWtmaWRDK1kKLS0tIDd6dXFBRG4rWEw1c0VScTVTS3ZI
            U3BOWTBJSnF0T3hFUDBRMWpYR3d5d00Kx0aIldd/FBGMFBJNV87de+2W50WJi2hV
            Zx9LVWelHM7sxYkUZAUAqVP9UjUINJKEQb/yffZWsDk1IoFC2BVU2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T18:32:47Z"
    mac: ENC[AES256_GCM,data:DvuQx1vpy0SDnPYNgATv0nGRXNYEw3yKbvMl/5OQ28qqd2d3O79IaScbuwGcXgL3JsI+ZhBuECIwSTzR2tyMGZitdmBOfGrnjHwsz7KCPVUQm9uRVGdroZBF5SZ0j42pZXyZx9xh+Er6Azi2XFoENn92Hknj3K/rRA1tqvM6nMU=,iv:j3ugm5bH5UAY3+KaEypI3bb/h4D0wWWZN/XuMhOpmGI=,tag:uLRJL+77GZciPZjgymgJTg==,type:str]
    encrypted_regex: ^(data|stringData|annotations)$
    version: 3.12.1
