apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
    namespace: beszel
type: Opaque
stringData:
    HUB_URL: ENC[AES256_GCM,data:VYvnuv39/0/ql66Pq6h2TKUdSiVF9n5FkQ==,iv:MGJ7i44HMnsCl7r51V7CrrXu6QDopg6x6J4KKPLFkKU=,tag:oGTvv8ndVh8Zd1/Oqc62MQ==,type:str]
    TOKEN: ENC[AES256_GCM,data:OfBQDNyGFoCBmehgcgju83ZCKLvZP37VHic0PQXPvAQXgJ31,iv:qMvKdgq0BWuho1VMildBvx7dBLmhGsfcLpHUUMrsfy0=,tag:9iEqpt5l9qtaNqU8aOMxHQ==,type:str]
    KEY: ENC[AES256_GCM,data:2oX9+Dvku8b4U2NeXl+gZw+1n2vtJy7hNuMlHLGKZJKCN9eu0d1+iPCqWxixurq8HbCOj9bwUvAO+q5FcR0cHxZ2AVeaoLtdVrJgM9RjeoA=,iv:sYXIKo4kcYBE4pPVHJW/yzg5wJEbCQa0HgLynX1wF1A=,tag:Zo+08YemhCvA/YRY7tTLPw==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSlJDdE8zMjZpZlcxQjNN
            RXVSb0Y3dHdRSzRJUUt5cjNJRWdDZ1NDbUNZCmJnaGFTd2R2Q0l3dnZQZTcwcUor
            bnZYSTZ4elNnUTVMNlhhOFZwbmNKTkUKLS0tIGo5NHIvaktoR1A4eE9ZNUVTVGN1
            Vi9RRVBxVnVsTjI4bm5OdDFQYlZiZ0kKZvYr6XnqekOqfhEdX5etJ5geFpX4OsKA
            oO2I94yb4/ig1+oy3Fan0YpvfitRrABiMFZrFpAOkUjv/CuEcB/vpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T18:55:35Z"
    mac: ENC[AES256_GCM,data:usY1+UH0IELaQpG3jKNlexp9MectNA/Q6Alit5ayM7RUqZektPomjR3RZdidfVfZZZa2UzVYVwkZbUYjihUzL2nVhX9ZNEKnFWbITUPb9rSfPKsqJb3FEJm99DykMPcbusALzgaOH2HSUYxtW+athXYVsQpVHLsIZ553TtHw18w=,iv:wFT+GyfNnxZabWrQw0LoQII8D/1tMpyD/N8OSHpOmGM=,tag:o+ac7B+y+tFcAcSC3pKiIg==,type:str]
    encrypted_regex: ^(data|stringData|annotations)$
    version: 3.12.1
