apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
    namespace: beszel
type: Opaque
stringData:
    HUB_URL: ENC[AES256_GCM,data:hmjLwfUacEI/rRSguTTiEicQfRERhDt/,iv:tY9+BB8HbN7oMNX3dnnlFAvOed6WGDCbRp5hiOdSDIw=,tag:BhC8do39l1aPMans0qDMEA==,type:str]
    TOKEN: ENC[AES256_GCM,data:OfBQDNyGFoCBmehgcgju83ZCKLvZP37VHic0PQXPvAQXgJ31,iv:qMvKdgq0BWuho1VMildBvx7dBLmhGsfcLpHUUMrsfy0=,tag:9iEqpt5l9qtaNqU8aOMxHQ==,type:str]
    KEY: ENC[AES256_GCM,data:2oX9+Dvku8b4U2NeXl+gZw+1n2vtJy7hNuMlHLGKZJKCN9eu0d1+iPCqWxixurq8HbCOj9bwUvAO+q5FcR0cHxZ2AVeaoLtdVrJgM9RjeoA=,iv:sYXIKo4kcYBE4pPVHJW/yzg5wJEbCQa0HgLynX1wF1A=,tag:Zo+08YemhCvA/YRY7tTLPw==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSlJDdE8zMjZpZlcxQjNN
            RXVSb0Y3dHdRSzRJUUt5cjNJRWdDZ1NDbUNZCmJnaGFTd2R2Q0l3dnZQZTcwcUor
            bnZYSTZ4elNnUTVMNlhhOFZwbmNKTkUKLS0tIGo5NHIvaktoR1A4eE9ZNUVTVGN1
            Vi9RRVBxVnVsTjI4bm5OdDFQYlZiZ0kKZvYr6XnqekOqfhEdX5etJ5geFpX4OsKA
            oO2I94yb4/ig1+oy3Fan0YpvfitRrABiMFZrFpAOkUjv/CuEcB/vpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T19:00:11Z"
    mac: ENC[AES256_GCM,data:AeAq3MpIIbqr6/lxWxsFzLirKGbNYD1dQL8rJKAvkFX8ii42k8v/AoxyPsN1ZGso/iebGZzHjGMup6JMVxPeCTcXmtfjZpw9qbRFEyQZnwYM2WVtszQO/ilwGodM2DwthMaDPbNYVRBHWq75Y6bWnYpqE6Q30MgGASmUnuXoQDw=,iv:Qzc0fMbM6LBwcZtSKT6778k1y9hMOFSNEW2+1ZZsI/w=,tag:d/VO498T0fSzyI93IBRHEg==,type:str]
    encrypted_regex: ^(data|stringData|annotations)$
    version: 3.12.1
