---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - https://github.com/rancher/system-upgrade-controller.git?ref=v0.19.2
    - https://github.com/rancher/system-upgrade-controller/releases/download/v0.19.2/crd.yaml
images:
    - name: rancher/system-upgrade-controller
      newTag: v0.19.2
patches:
    - target:
          kind: Deployment
          name: system-upgrade-controller
          namespace: system-upgrade
      patch: |-
          - op: add
            path: /spec/template/spec/tolerations/-
            value:
              key: k3s-controlplane
              operator: Equal
              value: "true"
              effect: NoSchedule
          - op: add
            path: /spec/template/spec/tolerations/-
            value:
              key: role
              operator: Equal
              value: "master"
              effect: NoSchedule
