apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql # WARNING: Removing this will also remove the volume
  - homepage
  - n8n
  - vaultwarden
  - cloudflare
  - weaveworks-dashboard
  - descheduler
  - mariadb-external
  - speedtest-tracker
  - linkwarden
  - linkstack
  - mariadb-operator
  - wordpress-dev-portfolio
  # -  netdata
  # - superset