apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql
  - homepage
  - n8n
  - vaultwarden
  - cloudflare
  - weaveworks-dashboard
  - descheduler
  # - mariadb
  - speedtest-tracker