apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  image:  mariadb:lts
  replicas: 3
  replication:
    enabled: true
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password

  service:
    type: LoadBalancer

  primaryService:
    type: LoadBalancer

  secondaryService:
    type: LoadBalancer

  
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  #   limits:
  #     cpu: 300m
  #     memory: 512Mi
  # galera:
  #   enabled: true
  #   primary:
  #     podIndex: 0
  #     automaticFailover: true
  #   sst: mariabackup
  #   replicaThreads: 1
  #   agent:
  #     image: ghcr.io/mariadb-operator/agent
  #     port: 5555
  #     kubernetesAuth:
  #       enabled: true
  #     gracefulShutdownTimeout: 5s
  #   recovery:
  #     enabled: true
  #     clusterHealthyTimeout: 3m
  #     clusterBootstrapTimeout: 10m
  #     podRecoveryTimeout: 5m
  #     podSyncTimeout: 5m
  #   initContainer:
  #     image: ghcr.io/mariadb-operator/init


  volumeClaimTemplate:
    resources:
      requests:
        storage: 3Gi
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce