apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  volumeClaimTemplate:
    resources:
      requests:
        storage: 3Gi
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce