apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  replicas: 3

  replication:
    enabled: true

  service:
    type: LoadBalancer

  primaryService:
    type: LoadBalancer

  secondaryService:
    type: LoadBalancer

  volumeClaimTemplate:
    resources:
      requests:
        storage: 3Gi
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce