apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-from-backup
spec:
  image: mariadb:lts
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password
  volumeClaimTemplate:
    resources:
      requests:
        storage: 3Gi
    accessModes:
      - ReadWriteOnce

  bootstrapFrom:
    backupRef:
      name: backup-scheduled
    targetRecoveryTime: 2024-02-19T09:00:00Z
