---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: helm
    - name: base
  path: ./clusters/experimental/core
  sourceRef:
    kind: GitRepository
    name: flux-system
