---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  path: ./infrastructure/cloudflare
  dependsOn:
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
