---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: descheduler
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: kube-system
  prune: true
  wait: true
  path: ./infrastructure/descheduler
  sourceRef:
    kind: GitRepository
    name: flux-system
