---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  interval: 1m
  prune: true
  wait: true
  path: ./infrastructure/prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
