---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: focalboard
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  path: ./apps/focalboard
  sourceRef:
    kind: GitRepository
    name: flux-system
