---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  path: ./helm
  sourceRef:
    kind: GitRepository
    name: flux-system
