---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: ingress-nginx
  prune: true
  wait: true
  path: ./infrastructure/ingress-nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
