---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
    # - name: snapshot-controller # additional CRDs
  interval: 1m
  prune: true
  wait: true
  path: ./infrastructure/longhorn
  sourceRef:
    kind: GitRepository
    name: flux-system
