---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mysql
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1m
  prune: true
  wait: true
  path: ./apps/mysql
  sourceRef:
    kind: GitRepository
    name: flux-system
