---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: longhorn
    - name: helm
  interval: 1m
  prune: true
  wait: true
  path: ./apps/postgresql
  sourceRef:
    kind: GitRepository
    name: flux-system
