---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: helm
  path: ./clusters/home/services
  sourceRef:
    kind: GitRepository
    name: flux-system
