---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  path: ./external-crds/snapshot-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
