apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter-crd
  namespace: kube-system
spec:
  interval: 1m
  wait: true
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: "./client/config/crd"

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: external-snapshotter-controller
  namespace: kube-system
spec:
  dependsOn:
    - name: external-snapshotter-crd
  interval: 1m
  wait: true
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: external-snapshotter
  path: "./deploy/kubernetes/snapshot-controller"
