---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vikunja
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1m
  prune: true
  wait: true
  path: ./apps/vikunja
  sourceRef:
    kind: GitRepository
    name: flux-system
