apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
spec:
  interval: 5m
  # install:
  #     crds: CreateReplace
  #     remediation:
  #         retries: 3
  # upgrade:
  #     crds: CreateReplace
  #     remediation:
  #         retries: 3
  chart:
    spec:
      chart: superset
      version: "0.11.x"
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system
      interval: 1m
  values:
      # Configure secret key, required to supress warnings that causes pod creation failures
    # envFromSecret: superset-secret

    # extraEnvRaw:
    #   - name: SECRET_KEY
    #     valueFrom:
    #       secretKeyRef:
    #         name: superset
    #         key: secret-key
    # Set postgresql credentials

    configOverrides:
      secret: |
        SECRET_KEY = 'AeDNQtvuCD2wkDk6jP3POLjYH4LVhHEey7oHzFJh2/2HaRC3LJAgCFbm'    
    postgresql:
      enabled: true
      auth:
        existingSecret: superset-db-secret # Located in ./secret.yaml
      
    # Configure persistence of the database in the cluster
      primary:
        persistence:
          enabled: true
          storageClass: longhorn 
          accessModes:
            - ReadWriteMany
          size: 5Gi

    # minimum values.yaml to enable clickhouse support for apache superset deployment
    bootstrapScript: |
      #!/bin/bash
      pip install clickhouse-connect>=0.6.8 && \
      if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

    # Apache superset master persistence
    master:
      persistence:
        enabled: true
        storageClass: longhorn 
        accessModes:
          - ReadWriteMany

    # service:
    #   type: LoadBalancer
    # Ingress for my environment
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 999m # Bypasses the 413 Request Entity Too Large error
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: SQL Editor & Visualizations
        gethomepage.dev/group: Apps/Services
        gethomepage.dev/icon: superset.png
        gethomepage.dev/name: Apache Superset
        gethomepage.dev/weight: "2"
      hosts:
        - host: superset.pacholoamit.com
          paths:
            - /