apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
spec:
  interval: 5m
  install:
      replace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      replace: true
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: superset
      version: "0.11.x"
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system
      interval: 1m
  values:
      # Configure secret key, required to supress warnings that causes pod creation failures
    envFromSecret: superset-secret


    configOverrides:
      secret: |
        SECRET_KEY = 'AeDNQtvuCD2wkDk6jP3POLjYH4LVhHEey7oHzFJh2/2HaRC3LJAgCFbm'    
    postgresql:
      enabled: true
      auth:
        existingSecret: superset-db-secret # Located in ./secret.yaml
      
    # Configure persistence of the database in the cluster
      primary:
        persistence:
          enabled: true
          storageClass: longhorn 
          accessModes:
            - ReadWriteMany
          size: 5Gi

    # minimum values.yaml to enable clickhouse support for apache superset deployment
    bootstrapScript: |
      #!/bin/bash
      pip install clickhouse-connect>=0.6.8 && \
      if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

    # Apache superset master persistence
    master:
      persistence:
        enabled: true
        storageClass: longhorn 
        accessModes:
          - ReadWriteMany

