apiVersion: v1
kind: Secret
metadata:
  name: superset
type: Opaque
stringData:
  DB_HOST: superset-postgresql
  DB_NAME: superset
  DB_PASS: fAdcZ88K4WvRMeGd2q4bsys6zf2QpU4muKyRrsRsp6tCvshT34oVwVsdfcXcLTxZjqurAvpoJbda
  DB_PORT: '5432'
  DB_USER: superset
  REDIS_HOST: superset-redis-headless
  REDIS_PORT: '6379'
  SECRET_KEY: AeDNQtvuCD2wkDk6jP3POLjYH4LVhHEey7oHzFJh2/2HaRC3LJAgCFbm
