apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
      replace: true
      
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
      cleanupOnFail: true
  chart:
    spec:
      chart: wordpress
      version: "23.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 50m
  values:
    image:
      debug: true
    wordpressUsername: pacholoamit
    existingSecret: wordpress
    wordpressEmail: pacholoamit.tech@gmail.com
    wordpressFirstName: Pacholo
    WordpressLastName: Amit
    wordpressBlogName: Pacholo Amit | Developer Portfolio
    wordpressExtraConfigContent: |
      @ini_set( 'post_max_size', '999M');
    replicaCount: 1
    topologySpreadConstraints:
       - maxSkew: 1
         topologyKey: kubernetes.io/hostname
         whenUnsatisfiable: DoNotSchedule
         labelSelector:
           matchLabels:
             app.kubernetes.io/name: wordpress
             app.kubernetes.io/instance: wordpress
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: www.pacholoamit.com
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Developer Portfolio
        gethomepage.dev/group: Apps/Services
        gethomepage.dev/icon: wordpress
        gethomepage.dev/name: Developer Portfolio
        gethomepage.dev/weight: "1"
      pathType: Prefix
      path: "/"
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteMany
      size: 5Gi
      existingClaim: wordpress
    mariadb:
      enabled: false
    externalDatabase:
      host: mariadb.default.svc.cluster.local # Reference mariadb deployment
      port: 3306
      user: root
      existingSecret: wordpress
      database: mariadb
    resources:
      limits: {}
      requests: 
        cpu: 500m
        memory: 1024Mi
