apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
      createNamespace: true
  chart:
    spec:
      chart: rancher
      version: "2.x.x"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      interval: 30m
  values:
    hostname: rancher.pacholoamit.com
    ingress:
      ingressClassName: nginx
      replicas: 1
      extraAnnotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Kubernetes management
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/icon: rancher
        gethomepage.dev/name: Rancher
        gethomepage.dev/weight: "1"
