apiVersion: v1
kind: Secret
metadata:
    name: checkmate-secrets
    namespace: checkmate
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Jf96Rpg73iExWVSoKrAphGBs6QMq4zmXU8gCnhJiHi4e4evt/6fm+5riARHy0n59Hd7BldODjz7rECXNkXRviw==,iv:FV5jAix96RsPfJur3a7zjvOQ5pBqS7cnXatJJ85JzSg=,tag:L1AiZY51soaSddrSos+DPQ==,type:str]
sops:
    age:
        - recipient: age19hfjt8tc0etz2swhums26jrsu8avaslpawkvrjcxj4tr0kwy6a2s4td64z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZU5CdXdtRXJVdFdNRW5o
            Q293ZHBWMVAyR3k4aHBBOWJVN1g5R2VWeWc4CmxjVHdqbXNlK2M4Q2QySllBSmtn
            NjArK1N5cVg0NTYrUjVFUExvL2tiMTAKLS0tIDhIcFcyQXBnYmZLbHB3WXlScDla
            WG9zK1BaZC9meFZJZGVBOGI2cGlVd1kKLytkuS/o09D9ssXusIiYa/og4qRN1U0g
            CZeL2PCuhfXSvj+xSqjWEAmsFAz6NlospGtw0j5vYZD9F5bnN73baw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T18:03:15Z"
    mac: ENC[AES256_GCM,data:RV6/v9ofpHTbGS6kmCBV5TbFR2zWt62yT0z4kdomaWw7qVIgN/g/2nFZQBy274Ox8xrqP+THws5nQXFxWsn7DCgyaiiYu8rirFe2vxzP66Uuw5LWyFuVg+Es7K+DO4olxbE9LRKl3qfa8fq2QjMx5qLYNcYtcNBKBbdwLADHXPc=,iv:ZPx8xB5mpB525WdNekSGMYBG37xSxpwv9NIJP0R9Xaw=,tag:f7mrwAf/+5SrGcvo6RgYSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
