---
reactiveresume:
    api:
        image: amruthpillai/reactive-resume:server-4.0.1
        port: 3100
        frontendUrl: https://resume.pacholoamit.com
    frontend:
        image: amruthpillai/reactive-resume:client-4.0.1
        port: 3000
