apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
spec:
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
      - name: speedtest-tracker
        imagePullPolicy: IfNotPresent
        image: ghcr.io/alexjustesen/speedtest-tracker
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: speedtest-tracker
          mountPath: /config  
        env:
        - name: TZ
          value: Asia/Manila
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: mariadb.default.svc.cluster.local
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: mariadb
        - name: DB_USERNAME
          value: pacholoamit
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-password
      volumes:
      - name: speedtest-tracker
        persistentVolumeClaim:
          claimName: speedtest-tracker

          
