apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: speedtest-tracker
      containers:
      - name: speedtest-tracker
        imagePullPolicy: IfNotPresent
        image: ghcr.io/alexjustesen/speedtest-tracker
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: speedtest-tracker
          mountPath: /config  
        env:
        - name: TZ
          value: Asia/Manila
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: mariadb-primary.mariadb-operator.svc.cluster.local
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: mariadb
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: speedtest-tracker
              key: mariadb-root-password
        - name: MAIL_MAILER
          value: smtp
        - name: MAIL_HOST
          value: smtp-relay.brevo.com
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: speedtest-tracker
              key: smtp-username
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: speedtest-tracker
              key: smtp-password
        - name: MAIL_FROM_ADDRESS
          value: speedtest@pacholoamit.com
        - name: MAIL_FROM_NAME
          value: Speedtest Tracker
      volumes:
      - name: speedtest-tracker
        persistentVolumeClaim:
          claimName: speedtest-tracker

          
