apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
spec:
  selector:
    app: speedtest-tracker
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest-tracker
  labels:
    name: speedtest-tracker
spec:
  rules:
  - host: speedtest.pacholoamit.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: speedtest-tracker
            port: 
              number: 80
