apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi