apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  install:
      createNamespace: true
      crds: CreateReplace
      remediation:
          retries: 3
  upgrade:
      crds: CreateReplace
      remediation:
          retries: 3
  chart:
    spec:
      chart: n8n
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: n8nio/n8n
      tag: 1.103.1
      pullPolicy: IfNotPresent
    replicaCount: 1
    service:
      type: LoadBalancer
    # extraEnvSecrets:
    #   DB_POSTGRESDB_PASSWORD:
    #     name: postgresql
    #     key: password
    config:
      generic:
        timezone: Asia/Manila
      host: n8n.pacholoamit.com
      protocol: https
      port: 443
      database:
        type: sqlite
        # postgresdb:
        #   host: postgresql.default.svc.cluster.local
        #   port: 5432
        #   database: postgresql
        #   user: pacholoamit

    persistence:
      enabled: true
      type: existing
      existingClaim: pvc-13c2362e-68a6-4532-ae4e-fc2-7f1d8185 # TODO: When rebuilding cluster, set this to n8n pvc
    
    extraEnv:
      WEBHOOK_TUNNEL_URL: https://n8n.pacholoamit.com
      WEBHOOK_URL: https://n8n.pacholoamit.com
      N8N_EDITOR_BASE_URL: https://n8n.pacholoamit.com
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 999m
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Open source workflow automation tool
        gethomepage.dev/group: Apps/Services
        gethomepage.dev/icon: n8n.png
        gethomepage.dev/name: n8n
        gethomepage.dev/weight: "2"
      hosts:
        - host: n8n.pacholoamit.com
          paths:
            - /