apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 999m
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Developer portfolio
    gethomepage.dev/group: Apps/Services
    gethomepage.dev/icon: wordpress.png
    gethomepage.dev/name: Developer Portfolio WP
spec:
  rules:
    - host: wp.pacholoamit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 8080
